set list on;
set count on;
select '============================================================' as separator from rdb$database;
select 'TABLE: ACTALARMS' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'ACTALARMS';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'ACTALARMS' order by rf.rdb$field_position;
select first 20 * from "ACTALARMS";
select '============================================================' as separator from rdb$database;
select 'TABLE: ALARMREAS' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'ALARMREAS';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'ALARMREAS' order by rf.rdb$field_position;
select first 20 * from "ALARMREAS";
select '============================================================' as separator from rdb$database;
select 'TABLE: ALLCHANGES' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'ALLCHANGES';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'ALLCHANGES' order by rf.rdb$field_position;
select first 20 * from "ALLCHANGES";
select '============================================================' as separator from rdb$database;
select 'TABLE: AREP' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'AREP';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'AREP' order by rf.rdb$field_position;
select first 20 * from "AREP";
select '============================================================' as separator from rdb$database;
select 'TABLE: CPTS_CHAN' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'CPTS_CHAN';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'CPTS_CHAN' order by rf.rdb$field_position;
select first 20 * from "CPTS_CHAN";
select '============================================================' as separator from rdb$database;
select 'TABLE: CPTS_INFO' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'CPTS_INFO';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'CPTS_INFO' order by rf.rdb$field_position;
select first 20 * from "CPTS_INFO";
select '============================================================' as separator from rdb$database;
select 'TABLE: CPTS_OBJ_INFO' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'CPTS_OBJ_INFO';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'CPTS_OBJ_INFO' order by rf.rdb$field_position;
select first 20 * from "CPTS_OBJ_INFO";
select '============================================================' as separator from rdb$database;
select 'TABLE: CPTS_PERSONAL' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'CPTS_PERSONAL';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'CPTS_PERSONAL' order by rf.rdb$field_position;
select first 20 * from "CPTS_PERSONAL";
select '============================================================' as separator from rdb$database;
select 'TABLE: DCT_CITY' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'DCT_CITY';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'DCT_CITY' order by rf.rdb$field_position;
select first 20 * from "DCT_CITY";
select '============================================================' as separator from rdb$database;
select 'TABLE: DCT_COUNTRY' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'DCT_COUNTRY';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'DCT_COUNTRY' order by rf.rdb$field_position;
select first 20 * from "DCT_COUNTRY";
select '============================================================' as separator from rdb$database;
select 'TABLE: DCT_REGION' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'DCT_REGION';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'DCT_REGION' order by rf.rdb$field_position;
select first 20 * from "DCT_REGION";
select '============================================================' as separator from rdb$database;
select 'TABLE: DELREAS' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'DELREAS';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'DELREAS' order by rf.rdb$field_position;
select first 20 * from "DELREAS";
select '============================================================' as separator from rdb$database;
select 'TABLE: DELREPORT' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'DELREPORT';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'DELREPORT' order by rf.rdb$field_position;
select first 20 * from "DELREPORT";
select '============================================================' as separator from rdb$database;
select 'TABLE: ECS' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'ECS';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'ECS' order by rf.rdb$field_position;
select first 20 * from "ECS";
select '============================================================' as separator from rdb$database;
select 'TABLE: EVLOG' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'EVLOG';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'EVLOG' order by rf.rdb$field_position;
select first 20 * from "EVLOG";
select '============================================================' as separator from rdb$database;
select 'TABLE: EVLOG_TMP' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'EVLOG_TMP';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'EVLOG_TMP' order by rf.rdb$field_position;
select first 20 * from "EVLOG_TMP";
select '============================================================' as separator from rdb$database;
select 'TABLE: FIXREAS' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'FIXREAS';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'FIXREAS' order by rf.rdb$field_position;
select first 20 * from "FIXREAS";
select '============================================================' as separator from rdb$database;
select 'TABLE: FIXREPORT' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'FIXREPORT';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'FIXREPORT' order by rf.rdb$field_position;
select first 20 * from "FIXREPORT";
select '============================================================' as separator from rdb$database;
select 'TABLE: FP_EVENTS' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'FP_EVENTS';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'FP_EVENTS' order by rf.rdb$field_position;
select first 20 * from "FP_EVENTS";
select '============================================================' as separator from rdb$database;
select 'TABLE: FP_TYPE_EVENT' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'FP_TYPE_EVENT';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'FP_TYPE_EVENT' order by rf.rdb$field_position;
select first 20 * from "FP_TYPE_EVENT";
select '============================================================' as separator from rdb$database;
select 'TABLE: GLOBALCFG' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'GLOBALCFG';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'GLOBALCFG' order by rf.rdb$field_position;
select first 20 * from "GLOBALCFG";
select '============================================================' as separator from rdb$database;
select 'TABLE: GPRSCFG' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'GPRSCFG';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'GPRSCFG' order by rf.rdb$field_position;
select first 20 * from "GPRSCFG";
select '============================================================' as separator from rdb$database;
select 'TABLE: GPS_SRV' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'GPS_SRV';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'GPS_SRV' order by rf.rdb$field_position;
select first 20 * from "GPS_SRV";
select '============================================================' as separator from rdb$database;
select 'TABLE: GRP_ECS' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'GRP_ECS';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'GRP_ECS' order by rf.rdb$field_position;
select first 20 * from "GRP_ECS";
select '============================================================' as separator from rdb$database;
select 'TABLE: GRPZN' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'GRPZN';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'GRPZN' order by rf.rdb$field_position;
select first 20 * from "GRPZN";
select '============================================================' as separator from rdb$database;
select 'TABLE: GUARD_GROUPS' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'GUARD_GROUPS';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'GUARD_GROUPS' order by rf.rdb$field_position;
select first 20 * from "GUARD_GROUPS";
select '============================================================' as separator from rdb$database;
select 'TABLE: HARDLOG' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'HARDLOG';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'HARDLOG' order by rf.rdb$field_position;
select first 20 * from "HARDLOG";
select '============================================================' as separator from rdb$database;
select 'TABLE: HCCHECKER' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'HCCHECKER';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'HCCHECKER' order by rf.rdb$field_position;
select first 20 * from "HCCHECKER";
select '============================================================' as separator from rdb$database;
select 'TABLE: IMAGES' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'IMAGES';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'IMAGES' order by rf.rdb$field_position;
select first 20 * from "IMAGES";
select '============================================================' as separator from rdb$database;
select 'TABLE: JOURNAL' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'JOURNAL';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'JOURNAL' order by rf.rdb$field_position;
select first 20 * from "JOURNAL";
select '============================================================' as separator from rdb$database;
select 'TABLE: LISTOFHOST' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'LISTOFHOST';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'LISTOFHOST' order by rf.rdb$field_position;
select first 20 * from "LISTOFHOST";
select '============================================================' as separator from rdb$database;
select 'TABLE: LOGSCONTROL' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'LOGSCONTROL';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'LOGSCONTROL' order by rf.rdb$field_position;
select first 20 * from "LOGSCONTROL";
select '============================================================' as separator from rdb$database;
select 'TABLE: MAINFO' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'MAINFO';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'MAINFO' order by rf.rdb$field_position;
select first 20 * from "MAINFO";
select '============================================================' as separator from rdb$database;
select 'TABLE: MESSLIST' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'MESSLIST';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'MESSLIST' order by rf.rdb$field_position;
select first 20 * from "MESSLIST";
select '============================================================' as separator from rdb$database;
select 'TABLE: OBJECTS' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'OBJECTS';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'OBJECTS' order by rf.rdb$field_position;
select first 20 * from "OBJECTS";
select '============================================================' as separator from rdb$database;
select 'TABLE: OBJECTS_GPS' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'OBJECTS_GPS';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'OBJECTS_GPS' order by rf.rdb$field_position;
select first 20 * from "OBJECTS_GPS";
select '============================================================' as separator from rdb$database;
select 'TABLE: OBJECTS_INFO' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'OBJECTS_INFO';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'OBJECTS_INFO' order by rf.rdb$field_position;
select first 20 * from "OBJECTS_INFO";
select '============================================================' as separator from rdb$database;
select 'TABLE: OBJECTS_LA' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'OBJECTS_LA';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'OBJECTS_LA' order by rf.rdb$field_position;
select first 20 * from "OBJECTS_LA";
select '============================================================' as separator from rdb$database;
select 'TABLE: OBJECTS_STATE' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'OBJECTS_STATE';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'OBJECTS_STATE' order by rf.rdb$field_position;
select first 20 * from "OBJECTS_STATE";
select '============================================================' as separator from rdb$database;
select 'TABLE: OBJECTS_VINFO2' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'OBJECTS_VINFO2';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'OBJECTS_VINFO2' order by rf.rdb$field_position;
select first 20 * from "OBJECTS_VINFO2";
select '============================================================' as separator from rdb$database;
select 'TABLE: OBJREGS' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'OBJREGS';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'OBJREGS' order by rf.rdb$field_position;
select first 20 * from "OBJREGS";
select '============================================================' as separator from rdb$database;
select 'TABLE: OBJTYPES' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'OBJTYPES';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'OBJTYPES' order by rf.rdb$field_position;
select first 20 * from "OBJTYPES";
select '============================================================' as separator from rdb$database;
select 'TABLE: PCN_RINFO' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'PCN_RINFO';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'PCN_RINFO' order by rf.rdb$field_position;
select first 20 * from "PCN_RINFO";
select '============================================================' as separator from rdb$database;
select 'TABLE: PERS_INSTALLER' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'PERS_INSTALLER';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'PERS_INSTALLER' order by rf.rdb$field_position;
select first 20 * from "PERS_INSTALLER";
select '============================================================' as separator from rdb$database;
select 'TABLE: PERS_MANAGER' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'PERS_MANAGER';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'PERS_MANAGER' order by rf.rdb$field_position;
select first 20 * from "PERS_MANAGER";
select '============================================================' as separator from rdb$database;
select 'TABLE: PERS_REGISTERED' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'PERS_REGISTERED';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'PERS_REGISTERED' order by rf.rdb$field_position;
select first 20 * from "PERS_REGISTERED";
select '============================================================' as separator from rdb$database;
select 'TABLE: PERSONAL' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'PERSONAL';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'PERSONAL' order by rf.rdb$field_position;
select first 20 * from "PERSONAL";
select '============================================================' as separator from rdb$database;
select 'TABLE: PPK' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'PPK';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'PPK' order by rf.rdb$field_position;
select first 20 * from "PPK";
select '============================================================' as separator from rdb$database;
select 'TABLE: PRSGROUP' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'PRSGROUP';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'PRSGROUP' order by rf.rdb$field_position;
select first 20 * from "PRSGROUP";
select '============================================================' as separator from rdb$database;
select 'TABLE: PULT_INFO' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'PULT_INFO';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'PULT_INFO' order by rf.rdb$field_position;
select first 20 * from "PULT_INFO";
select '============================================================' as separator from rdb$database;
select 'TABLE: RADIO_PPK' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'RADIO_PPK';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'RADIO_PPK' order by rf.rdb$field_position;
select first 20 * from "RADIO_PPK";
select '============================================================' as separator from rdb$database;
select 'TABLE: SBS' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'SBS';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'SBS' order by rf.rdb$field_position;
select first 20 * from "SBS";
select '============================================================' as separator from rdb$database;
select 'TABLE: SBS_ACTIV' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'SBS_ACTIV';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'SBS_ACTIV' order by rf.rdb$field_position;
select first 20 * from "SBS_ACTIV";
select '============================================================' as separator from rdb$database;
select 'TABLE: SBS_PORT' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'SBS_PORT';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'SBS_PORT' order by rf.rdb$field_position;
select first 20 * from "SBS_PORT";
select '============================================================' as separator from rdb$database;
select 'TABLE: SMS_MESS' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'SMS_MESS';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'SMS_MESS' order by rf.rdb$field_position;
select first 20 * from "SMS_MESS";
select '============================================================' as separator from rdb$database;
select 'TABLE: SMS_TEXT' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'SMS_TEXT';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'SMS_TEXT' order by rf.rdb$field_position;
select first 20 * from "SMS_TEXT";
select '============================================================' as separator from rdb$database;
select 'TABLE: SOFT_VER' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'SOFT_VER';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'SOFT_VER' order by rf.rdb$field_position;
select first 20 * from "SOFT_VER";
select '============================================================' as separator from rdb$database;
select 'TABLE: SRVLSTACT' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'SRVLSTACT';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'SRVLSTACT' order by rf.rdb$field_position;
select first 20 * from "SRVLSTACT";
select '============================================================' as separator from rdb$database;
select 'TABLE: TAREP' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'TAREP';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'TAREP' order by rf.rdb$field_position;
select first 20 * from "TAREP";
select '============================================================' as separator from rdb$database;
select 'TABLE: TFORALARMSREPORT' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'TFORALARMSREPORT';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'TFORALARMSREPORT' order by rf.rdb$field_position;
select first 20 * from "TFORALARMSREPORT";
select '============================================================' as separator from rdb$database;
select 'TABLE: UR_PARAMS' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'UR_PARAMS';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'UR_PARAMS' order by rf.rdb$field_position;
select first 20 * from "UR_PARAMS";
select '============================================================' as separator from rdb$database;
select 'TABLE: USERSTATUS' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'USERSTATUS';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'USERSTATUS' order by rf.rdb$field_position;
select first 20 * from "USERSTATUS";
select '============================================================' as separator from rdb$database;
select 'TABLE: XOZORG' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'XOZORG';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'XOZORG' order by rf.rdb$field_position;
select first 20 * from "XOZORG";
select '============================================================' as separator from rdb$database;
select 'TABLE: ZONES' as table_name from rdb$database;
select coalesce(cast(rdb$description as varchar(8191)), '(no table description)') as table_description from rdb$relations where rdb$relation_name = 'ZONES';
select trim(rf.rdb$field_name) as field_name, coalesce(cast(rf.rdb$description as varchar(8191)), cast(f.rdb$description as varchar(8191)), '(no field description)') as field_description from rdb$relation_fields rf join rdb$fields f on f.rdb$field_name = rf.rdb$field_source where rf.rdb$relation_name = 'ZONES' order by rf.rdb$field_position;
select first 20 * from "ZONES";
quit;

