
SET SQL DIALECT 3; 

/* CREATE DATABASE '127.0.0.1:C:\MOST.PM\BASE\MOST5.FDB' PAGE_SIZE 4096 DEFAULT CHARACTER SET WIN1251; */


/*  Generators or sequences */
CREATE GENERATOR GEN_AI_MAINFO;
CREATE GENERATOR GEN_ALLCHANGES_ID;
CREATE GENERATOR GEN_DCT_CITY;
CREATE GENERATOR GEN_DCT_CNTR;
CREATE GENERATOR GEN_DCT_RG;
CREATE GENERATOR GEN_FOR_AI_ACTALARMS;
CREATE GENERATOR GEN_FOR_AI_ALARMREAS;
CREATE GENERATOR GEN_FOR_AI_AREP;
CREATE GENERATOR GEN_FOR_AI_CPTS_CHAN;
CREATE GENERATOR GEN_FOR_AI_CPTS_INFO;
CREATE GENERATOR GEN_FOR_AI_CPTS_OBJ_INFO;
CREATE GENERATOR GEN_FOR_AI_CPTS_PERSONAL;
CREATE GENERATOR GEN_FOR_AI_DELREAS;
CREATE GENERATOR GEN_FOR_AI_DELREPORT;
CREATE GENERATOR GEN_FOR_AI_ECS;
CREATE GENERATOR GEN_FOR_AI_EVLOG;
CREATE GENERATOR GEN_FOR_AI_FIXREAS;
CREATE GENERATOR GEN_FOR_AI_FIXREPORT;
CREATE GENERATOR GEN_FOR_AI_GLOBALCFG;
CREATE GENERATOR GEN_FOR_AI_GPS_SRV;
CREATE GENERATOR GEN_FOR_AI_GRP_ECS;
CREATE GENERATOR GEN_FOR_AI_GUARD_GROUPS;
CREATE GENERATOR GEN_FOR_AI_HARDLOG;
CREATE GENERATOR GEN_FOR_AI_IMAGES;
CREATE GENERATOR GEN_FOR_AI_JOURNAL;
CREATE GENERATOR GEN_FOR_AI_MESSLIST;
CREATE GENERATOR GEN_FOR_AI_OBJECTS;
CREATE GENERATOR GEN_FOR_AI_OBJECTS_GPS;
CREATE GENERATOR GEN_FOR_AI_OBJECTS_INFO;
CREATE GENERATOR GEN_FOR_AI_OBJECTS_LA;
CREATE GENERATOR GEN_FOR_AI_OBJECTS_STATE;
CREATE GENERATOR GEN_FOR_AI_OBJECTS_VINFO2;
CREATE GENERATOR GEN_FOR_AI_OBJREGS;
CREATE GENERATOR GEN_FOR_AI_OBJTYPES;
CREATE GENERATOR GEN_FOR_AI_PERSONAL;
CREATE GENERATOR GEN_FOR_AI_PERS_INSTALLER;
CREATE GENERATOR GEN_FOR_AI_PERS_MANAGER;
CREATE GENERATOR GEN_FOR_AI_PPK;
CREATE GENERATOR GEN_FOR_AI_PRSGROUP;
CREATE GENERATOR GEN_FOR_AI_PULT_INFO;
CREATE GENERATOR GEN_FOR_AI_SBS;
CREATE GENERATOR GEN_FOR_AI_SBS_ACTIV;
CREATE GENERATOR GEN_FOR_AI_SBS_PORT;
CREATE GENERATOR GEN_FOR_AI_SMS_MESS;
CREATE GENERATOR GEN_FOR_AI_SMS_TEXT;
CREATE GENERATOR GEN_FOR_AI_TAREP;
CREATE GENERATOR GEN_FOR_AI_UR_PARAMS;
CREATE GENERATOR GEN_FOR_AI_XOZORG;
CREATE GENERATOR GEN_FOR_AI_ZONES;
CREATE GENERATOR GEN_FP_EVENTS_ID;
CREATE GENERATOR GEN_FP_TYPE_EVENT_ID;
CREATE GENERATOR GEN_GRPZN_ID;
CREATE GENERATOR GEN_PCN_RINFO;
CREATE GENERATOR GEN_PREG;
CREATE GENERATOR GEN_RADIO_PPK_ID;
CREATE GENERATOR GEN_SV;

/* Domain definitions */
CREATE DOMAIN DOM_BYTE AS SMALLINT;
CREATE DOMAIN DOM_DATE AS TIMESTAMP;
CREATE DOMAIN DOM_INFO AS VARCHAR(100);
CREATE DOMAIN DOM_INTEGER AS INTEGER;
CREATE DOMAIN DOM_N_ID AS BIGINT NOT NULL;
CREATE DOMAIN DOM_STRING_20 AS VARCHAR(20);
COMMIT WORK;

/* Table: ACTALARMS, Owner: SYSDBA */
CREATE TABLE ACTALARMS (ID BIGINT NOT NULL,
        EVTIME1 TIMESTAMP,
        OBJUIN BIGINT,
        OBJN BIGINT,
        EVUIN BIGINT,
        CARDOPENED1 BIGINT,
        SCENERYID BIGINT,
        BTN1 BIGINT,
        BTN2 BIGINT,
        BTN3 BIGINT,
        BTN4 BIGINT,
        BTN5 BIGINT,
        BTN6 BIGINT,
        BTN7 BIGINT,
        BTN8 BIGINT,
        BTN9 BIGINT,
        BTN10 BIGINT,
        GRPN SMALLINT,
        ZONEN SMALLINT,
        OBJSHORTNAME1 VARCHAR(102),
        RUS1 VARCHAR(122),
        INFO1 VARCHAR(202),
        RESBYTE1 BIGINT,
        RESBIGINT1 BIGINT,
        RESBIGINT2 BIGINT,
        RESVARCHAR1 VARCHAR(102),
        RESVARCHAR2 VARCHAR(102),
        ADDPARAM SMALLINT,
        BTN11 BIGINT,
CONSTRAINT PK_ACTALARMS PRIMARY KEY (ID));

/* Table: ALARMREAS, Owner: SYSDBA */
CREATE TABLE ALARMREAS (ID BIGINT NOT NULL,
        REASON1 VARCHAR(102),
        RESBYTE1 BIGINT,
        RESBIGINT1 BIGINT,
        RESBIGINT2 BIGINT,
        RESVARCHAR1 VARCHAR(102),
        RESVARCHAR2 VARCHAR(102),
CONSTRAINT PK_ALARMREAS PRIMARY KEY (ID));

/* Table: ALLCHANGES, Owner: SYSDBA */
CREATE TABLE ALLCHANGES (ID BIGINT NOT NULL,
        SQL_TEXT VARCHAR(30000),
        DATE_CHANGE TIMESTAMP DEFAULT 'NOW',
        NAME_GEN VARCHAR(25),
CONSTRAINT PK_ALLCHANGES PRIMARY KEY (ID));

/* Table: AREP, Owner: SYSDBA */
CREATE TABLE AREP (ID BIGINT NOT NULL,
        OBJN BIGINT,
        OBJSHORTNAME1 VARCHAR(102),
        ADDRESS1 VARCHAR(202),
        INFORMED VARCHAR(202),
        DT_ALARM TIMESTAMP,
        DT_INFORMED TIMESTAMP,
CONSTRAINT PK_AREP PRIMARY KEY (ID));

/* Table: CPTS_CHAN, Owner: SYSDBA */
CREATE TABLE CPTS_CHAN (ID BIGINT NOT NULL,
        CHAN_INFO VARCHAR(70),
        NOTES1 VARCHAR(102),
        BLOCKED SMALLINT DEFAULT 0 NOT NULL,
        ACCESS_LVL SMALLINT DEFAULT 0 NOT NULL,
CONSTRAINT PK_CPTS_CHAN PRIMARY KEY (ID));

/* Table: CPTS_INFO, Owner: SYSDBA */
CREATE TABLE CPTS_INFO (ID BIGINT NOT NULL,
        CPTS_NAME VARCHAR(140),
        CPTS_LIC_SERIA VARCHAR(10),
        CPTS_LIC_NUM VARCHAR(10),
        CPTS_LIC_DT TIMESTAMP,
        CPTS_LOCATION VARCHAR(140),
        CPTS_IDC VARCHAR(160),
CONSTRAINT PK_CPTS_INFO PRIMARY KEY (ID));

/* Table: CPTS_OBJ_INFO, Owner: SYSDBA */
CREATE TABLE CPTS_OBJ_INFO (ID BIGINT NOT NULL,
        OBJN BIGINT,
        OBJUIN BIGINT,
        ST_RO SMALLINT,
        LO_D BIGINT,
        LO_M BIGINT,
        LO_S BIGINT,
        LA_D BIGINT,
        LA_M BIGINT,
        LA_S BIGINT,
        SERV_ORG_TYPE VARCHAR(80),
        SERV_ORG_NAME VARCHAR(80),
        SERV_ORG_IDC VARCHAR(40),
        CDT_1 TIMESTAMP,
        CDT_2 TIMESTAMP,
        REM_NAME VARCHAR(80),
        REM_ADR VARCHAR(80),
        REM_PHONE VARCHAR(80),
        ADD_INFO VARCHAR(160),
CONSTRAINT PK_CPTS_OBJ_INFO PRIMARY KEY (ID));

/* Table: CPTS_PERSONAL, Owner: SYSDBA */
CREATE TABLE CPTS_PERSONAL (ID BIGINT NOT NULL,
        SURNAME1 VARCHAR(62),
        NAME1 VARCHAR(30),
        SECNAME1 VARCHAR(34),
        NOTES1 VARCHAR(102),
        BLOCKED SMALLINT DEFAULT 0 NOT NULL,
        ACCESS_LVL SMALLINT DEFAULT 0 NOT NULL,
CONSTRAINT PK_CPTS_PERSONAL PRIMARY KEY (ID));

/* Table: DCT_CITY, Owner: SYSDBA */
CREATE TABLE DCT_CITY (ID BIGINT,
        CI_IND BIGINT,
        RG_IND BIGINT,
        CO_IND BIGINT,
        CI_NAME VARCHAR(40));

/* Table: DCT_COUNTRY, Owner: SYSDBA */
CREATE TABLE DCT_COUNTRY (ID BIGINT,
        CO_IND BIGINT,
        CNTR_NAME VARCHAR(40));

/* Table: DCT_REGION, Owner: SYSDBA */
CREATE TABLE DCT_REGION (ID BIGINT,
        RG_IND BIGINT,
        CO_IND BIGINT,
        RG_NAME VARCHAR(40));

/* Table: DELREAS, Owner: SYSDBA */
CREATE TABLE DELREAS (ID BIGINT NOT NULL,
        REASON1 VARCHAR(102),
CONSTRAINT PK_DELREAS PRIMARY KEY (ID));

/* Table: DELREPORT, Owner: SYSDBA */
CREATE TABLE DELREPORT (ID BIGINT NOT NULL,
        OBJN BIGINT,
        OBJSHORTNAME1 VARCHAR(102),
        ADDRESS1 VARCHAR(202),
        PHONES1 VARCHAR(102),
        REASONDEL VARCHAR(102),
        INFORMED VARCHAR(202),
        DT_DEL TIMESTAMP,
        DT_INFORMED TIMESTAMP,
CONSTRAINT PK_DELREPORT PRIMARY KEY (ID));

/* Table: ECS, Owner: SYSDBA */
CREATE TABLE ECS (ID BIGINT,
        OBJUIN BIGINT,
        OBJN BIGINT,
        GRPN BIGINT,
        ECN BIGINT,
        ECNAME VARCHAR(202),
        ECSTATE SMALLINT,
        ECSTATE_TECHALARM SMALLINT,
        ECTYPE1 SMALLINT,
        ECDESCR1 VARCHAR(202),
        ECGRP BIGINT DEFAULT 0);

/* Table: EVLOG, Owner: SYSDBA */
CREATE TABLE EVLOG (ID BIGINT NOT NULL,
        EVTIME1 TIMESTAMP,
        OBJUIN BIGINT,
        GRPN BIGINT,
        ZONEN BIGINT,
        EVUIN BIGINT,
        INFO1 VARCHAR(202),
        RESBYTE1 BIGINT,
        RESBIGINT1 BIGINT,
        RESBIGINT2 BIGINT,
        RESVARCHAR1 VARCHAR(102),
        RESVARCHAR2 VARCHAR(102),
        FIRSTACTDTIME TIMESTAMP,
        FIRSTACTWASALERTED SMALLINT,
        XONUM BIGINT DEFAULT 0,
CONSTRAINT PK_EVLOG PRIMARY KEY (ID));

/* Table: EVLOG_TMP, Owner: SYSDBA */
CREATE TABLE EVLOG_TMP (ID BIGINT,
        EVTIME1 TIMESTAMP,
        OBJUIN BIGINT,
        GRPN BIGINT,
        ZONEN BIGINT,
        EVUIN BIGINT,
        INFO1 VARCHAR(202));

/* Table: FIXREAS, Owner: SYSDBA */
CREATE TABLE FIXREAS (ID BIGINT NOT NULL,
        REASON1 VARCHAR(102),
CONSTRAINT PK_FIXREAS PRIMARY KEY (ID));

/* Table: FIXREPORT, Owner: SYSDBA */
CREATE TABLE FIXREPORT (ID BIGINT NOT NULL,
        OBJN BIGINT,
        OBJSHORTNAME1 VARCHAR(102),
        ADDRESS1 VARCHAR(202),
        PHONES1 VARCHAR(102),
        REASONFIX VARCHAR(102),
        DT_FIX TIMESTAMP,
        DT_SET TIMESTAMP,
CONSTRAINT PK_FIXREPORT PRIMARY KEY (ID));

/* Table: FP_EVENTS, Owner: SYSDBA */
CREATE TABLE FP_EVENTS (FP_N_ID DOM_N_ID,
        FP_DATE DOM_DATE,
        FP_TYPE DOM_N_ID,
        FP_INFO DOM_INFO,
        FP_NUMBER_OBJECT DOM_STRING_20,
        FP_NUMBER_GROUP DOM_STRING_20,
        FP_NUMBER_ZONE DOM_STRING_20,
        ADDINFO VARCHAR(2000),
        ARRIVALTIME TIMESTAMP,
        ALARMID BIGINT,
        ALARMSTATE SMALLINT,
CONSTRAINT PK_FP_EVENTS PRIMARY KEY (FP_N_ID));

/* Table: FP_TYPE_EVENT, Owner: SYSDBA */
CREATE TABLE FP_TYPE_EVENT (TE_N_ID DOM_N_ID,
        TE_NAME DOM_STRING_20,
CONSTRAINT PK_FP_TYPE_EVENT PRIMARY KEY (TE_N_ID));

/* Table: GLOBALCFG, Owner: SYSDBA */
CREATE TABLE GLOBALCFG (ID BIGINT NOT NULL,
        PERSONALID BIGINT,
        COLORALARM BIGINT,
        TEXTCOLORALARM BIGINT,
        COLORTECHALARM BIGINT,
        TEXTCOLORTECHALARM BIGINT,
        COLORCONNFAILED BIGINT,
        TEXTCOLORCONNFAILED BIGINT,
        COLORARMEDON BIGINT,
        TEXTCOLORARMEDON BIGINT,
        COLORARMEDOFF BIGINT,
        TEXTCOLORARMEDOFF BIGINT,
        COLORPARTARMEDON BIGINT,
        TEXTCOLORPARTARMEDON BIGINT,
        COLORPARTARMEDOFF BIGINT,
        TEXTCOLORPARTARMEDOFF BIGINT,
        COLORRESTORE BIGINT,
        TEXTCOLORRESTORE BIGINT,
        COLORINFO BIGINT,
        TEXTCOLORINFO BIGINT,
        COLORREPAIR BIGINT,
        TEXTCOLORREPAIR BIGINT,
        EVNTSTIMESHOW SMALLINT,
        EVNTSTIMESHOWFROM VARCHAR(10),
        ALLOWGRBDOWN SMALLINT,
        ONLYMOST9X SMALLINT,
        DISABLETASKMANAGERNT SMALLINT,
        SEARCHPRIORITY SMALLINT,
        ALLOWMINIMIZE SMALLINT,
        HIDETASKBAR SMALLINT,
        DONTSHOWALARMCARD SMALLINT,
        REOPENALARMCARDATSTARTUP SMALLINT,
        STOPPLAYINGBYESCAPE SMALLINT,
        STOPPLAYINGBYPM SMALLINT,
        STOPPLAYINGBYANYKEY SMALLINT,
        REDALARMSOUNDISMAIN SMALLINT,
        USINGAGS SMALLINT,
        RESERV1 SMALLINT,
        RESERV2 SMALLINT,
        RESERV3 SMALLINT,
        RESERV4 SMALLINT,
        RESERV5 SMALLINT,
        A220V_NEED SMALLINT DEFAULT 0,
        A220V_PERIOD BIGINT DEFAULT 5,
        A220V_TRANSPARENT SMALLINT DEFAULT 0,
        EVNTSTIMESHOWMAX BIGINT DEFAULT 100,
        CLOSEALLALARMS SMALLINT DEFAULT 0,
        AGAON_NEED SMALLINT DEFAULT 0,
        AGAON_PERIOD BIGINT DEFAULT 5,
        AGAON_TRANSPARENT SMALLINT DEFAULT 0,
        USEALTALARMCARDRT SMALLINT,
CONSTRAINT PK_GLOBALCFG PRIMARY KEY (ID));

/* Table: GPRSCFG, Owner: SYSDBA */
CREATE TABLE GPRSCFG (USECOMPORT SMALLINT);

/* Table: GPS_SRV, Owner: SYSDBA */
CREATE TABLE GPS_SRV (ID BIGINT,
        GRP_IS_MOBIL SMALLINT,
        SRV_HOST VARCHAR(80),
        SRV_INFO VARCHAR(100),
        CALLBACKURL VARCHAR(100));

/* Table: GRPZN, Owner: SYSDBA */
CREATE TABLE GRPZN (ID BIGINT NOT NULL,
        OBJUIN BIGINT,
        OBJN BIGINT,
        GRP_NUM INTEGER NOT NULL,
        GRP_NAME VARCHAR(50),
        GRP_INFO VARCHAR(128),
        GRP_GUARDSTATE SMALLINT DEFAULT 0,
        GRP_ALARMSTATE SMALLINT DEFAULT 0,
        GRP_TECHALARMSTATE SMALLINT DEFAULT 0,
        GRP_ISCONNSTATE SMALLINT DEFAULT 0,
        GRP_POWERFAULT SMALLINT DEFAULT 0,
CONSTRAINT PK_GRPZN PRIMARY KEY (ID));

/* Table: GRP_ECS, Owner: SYSDBA */
CREATE TABLE GRP_ECS (ID BIGINT NOT NULL,
        OBJUIN BIGINT,
        OBJN BIGINT,
        GRPN BIGINT,
        GRP_NUM INTEGER NOT NULL,
        GRP_NAME VARCHAR(50),
        GRP_INFO VARCHAR(128),
        GRP_STATE SMALLINT DEFAULT 0,
        GRP_TECHALARMSTATE SMALLINT DEFAULT 0,
CONSTRAINT PK_GRP_ECS PRIMARY KEY (ID));

/* Table: GUARD_GROUPS, Owner: SYSDBA */
CREATE TABLE GUARD_GROUPS (ID BIGINT,
        GRP_NUM BIGINT,
        GRP_TRACK BIGINT,
        GRP_NAME VARCHAR(50),
        GRP_DESCRIPTION VARCHAR(128),
        GRP_IS_MOBIL SMALLINT DEFAULT 0);

/* Table: HARDLOG, Owner: SYSDBA */
CREATE TABLE HARDLOG (ID BIGINT NOT NULL,
        PROTID BIGINT,
        RECTIME1 TIMESTAMP,
        OBJN BIGINT,
        GRPN BIGINT,
        ZONEN SMALLINT,
        MESSID BIGINT,
        INFO1 VARCHAR(202),
        RESBYTE1 BIGINT,
CONSTRAINT PK_HARDLOG PRIMARY KEY (ID));

/* Table: HCCHECKER, Owner: SYSDBA */
CREATE TABLE HCCHECKER (HCTEST VARCHAR(200),
        HCTEST2 VARCHAR(80) DEFAULT '');

/* Table: IMAGES, Owner: SYSDBA */
CREATE TABLE IMAGES (ID BIGINT NOT NULL,
        OBJUIN BIGINT,
        IMGFILE1 VARCHAR(512),
        IMGDESCR1 VARCHAR(512),
        ZONEID1 BIGINT,
        SORT1 BIGINT,
        RESBYTE1 BIGINT,
CONSTRAINT PK_IMAGES PRIMARY KEY (ID));

/* Table: JOURNAL, Owner: SYSDBA */
CREATE TABLE JOURNAL (ID BIGINT NOT NULL,
        JTIME1 TIMESTAMP,
        JOBJUIN BIGINT,
        JRECTEXT VARCHAR(202),
        JWRITER VARCHAR(102),
        JCATEGORY BIGINT,
        JRESERVLONG BIGINT,
        JRESERVTIME TIMESTAMP,
        RESBYTE1 BIGINT,
CONSTRAINT PK_JOURNAL PRIMARY KEY (ID));

/* Table: LISTOFHOST, Owner: SYSDBA */
CREATE TABLE LISTOFHOST (TESTEDHOSTNAME VARCHAR(100),
        TRY_N SMALLINT);

/* Table: LOGSCONTROL, Owner: SYSDBA */
CREATE TABLE LOGSCONTROL (MAINLOGFULL SMALLINT,
        ALTLOGFULL SMALLINT,
        MAINLOGFILED SMALLINT,
        ALTLOGFILED SMALLINT,
        MAINLOGRC BIGINT,
        ALTLOGRC BIGINT,
        MAINLOGMAXRC BIGINT,
        ALTLOGMAXRC BIGINT);

/* Table: MAINFO, Owner: SYSDBA */
CREATE TABLE MAINFO (ID BIGINT NOT NULL,
        MESSID BIGINT,
        ACODE BIGINT,
        INFO VARCHAR(102));

/* Table: MESSLIST, Owner: SYSDBA */
CREATE TABLE MESSLIST (UIN BIGINT NOT NULL,
        PROTID BIGINT,
        MESSID BIGINT,
        RUS1 VARCHAR(122),
        ENG1 VARCHAR(202),
        SC1 BIGINT,
        OBJN BIGINT,
        GRPN BIGINT,
        ZONEN SMALLINT,
        RESBYTE1 BIGINT,
        UKR1 VARCHAR(122),
        MESSIDHEX VARCHAR(122),
        RESVARCHAR1 VARCHAR(122),
        FORADMINONLY SMALLINT,
        MC220V SMALLINT DEFAULT 0,
CONSTRAINT PK_MESSLIST PRIMARY KEY (UIN));

/* Table: OBJECTS, Owner: SYSDBA */
CREATE TABLE OBJECTS (OBJUIN BIGINT NOT NULL,
        OBJN BIGINT,
        GRPN BIGINT,
        OBJFULLNAME1 VARCHAR(202),
        OBJSHORTNAME1 VARCHAR(102),
        OBJTYPEID BIGINT,
        ADDRESS1 VARCHAR(202),
        PHONES1 VARCHAR(102),
        GUARDSTATE1 BIGINT,
        ALARMSTATE1 BIGINT,
        TECHALARMSTATE1 BIGINT,
        ISCONNSTATE1 BIGINT,
        OBJREGID SMALLINT,
        CONTRACT1 VARCHAR(22),
        LOCATION1 VARCHAR(3072),
        NOTES1 VARCHAR(3072),
        LASTEVID BIGINT,
        LASTEVTIME1 TIMESTAMP,
        ATIMEON1 TIMESTAMP,
        ATIMEOFF1 TIMESTAMP,
        ATIMEON2 TIMESTAMP,
        ATIMEOFF2 TIMESTAMP,
        ATIMEON3 TIMESTAMP,
        ATIMEOFF3 TIMESTAMP,
        ATIMEON4 TIMESTAMP,
        ATIMEOFF4 TIMESTAMP,
        ATIMEON5 TIMESTAMP,
        ATIMEOFF5 TIMESTAMP,
        ATIMEON6 TIMESTAMP,
        ATIMEOFF6 TIMESTAMP,
        ATIMEON7 TIMESTAMP,
        ATIMEOFF7 TIMESTAMP,
        TIMECONTROL1 BIGINT,
        TESTCONTROL1 BIGINT,
        TESTTIME1 BIGINT,
        NEXTTESTTIME1 TIMESTAMP,
        LASTTESTTIME1 TIMESTAMP,
        OBJPRIORITY1 BIGINT,
        PPKID BIGINT,
        ENG1 BIGINT,
        ENG2 BIGINT,
        ENG3 BIGINT,
        XOZORGID BIGINT,
        RESERVTEXT VARCHAR(102),
        RESERVLONG1 BIGINT,
        RESERVLONG2 BIGINT,
        RESERVDATA1 TIMESTAMP,
        RESERVDATA2 TIMESTAMP,
        RESERVPHONE1 VARCHAR(42),
        RESERVPHONE2 VARCHAR(42),
        GSMPHONE VARCHAR(32),
        GSMACCOUNT TIMESTAMP,
        GSMHIDENINT BIGINT,
        GSMFLATCODEINT BIGINT,
        OBJCHAN BIGINT,
        RESBYTE1 BIGINT,
        GRPPERS BIGINT,
        OLDGRPPERS BIGINT,
        POWERFAULT BIGINT,
        RESBIGINT1 BIGINT,
        RESBIGINT2 BIGINT,
        RESVARCHAR1 VARCHAR(102),
        RESVARCHAR2 VARCHAR(102),
        FCNEW BIGINT,
        FCOLD BIGINT,
        OBJCHAN2 BIGINT,
        RESBYTE2 BIGINT,
        FCNEW2 BIGINT,
        FCOLD2 BIGINT,
        ISZONEOFF SMALLINT DEFAULT 0 NOT NULL,
        GPRS_IDPS SMALLINT,
        GPRS_IDPS_OLD SMALLINT,
        DAT0S SMALLINT,
        DAT1S SMALLINT,
        DAT0S_OLD SMALLINT,
        DAT1S_OLD SMALLINT,
        GSMPHONE2 VARCHAR(32),
        TESTCONTROL2 BIGINT,
        TESTTIME2 BIGINT,
        CURRENT_CHAN SMALLINT,
        LASTACTIVEGSMPHONE SMALLINT DEFAULT 0,
CONSTRAINT PK_OBJECTS PRIMARY KEY (OBJUIN));

/* Table: OBJECTS_GPS, Owner: SYSDBA */
CREATE TABLE OBJECTS_GPS (ID BIGINT,
        OBJUIN BIGINT,
        OBJN BIGINT,
        GRPN BIGINT,
        LATITUDE VARCHAR(20),
        LONGITUDE VARCHAR(20),
        NAV_ID BIGINT);

/* Table: OBJECTS_INFO, Owner: SYSDBA */
CREATE TABLE OBJECTS_INFO (OBJUIN BIGINT NOT NULL,
        OBJN BIGINT,
        GRPN BIGINT,
        OBJFULLNAME1 VARCHAR(202),
        OBJSHORTNAME1 VARCHAR(102),
        OBJTYPEID BIGINT,
        ADDRESS1 VARCHAR(202),
        PHONES1 VARCHAR(102),
        OBJREGID SMALLINT,
        CONTRACT1 VARCHAR(22),
        LOCATION1 VARCHAR(3072),
        NOTES1 VARCHAR(3072),
        ATIMEON1 TIMESTAMP,
        ATIMEOFF1 TIMESTAMP,
        ATIMEON2 TIMESTAMP,
        ATIMEOFF2 TIMESTAMP,
        ATIMEON3 TIMESTAMP,
        ATIMEOFF3 TIMESTAMP,
        ATIMEON4 TIMESTAMP,
        ATIMEOFF4 TIMESTAMP,
        ATIMEON5 TIMESTAMP,
        ATIMEOFF5 TIMESTAMP,
        ATIMEON6 TIMESTAMP,
        ATIMEOFF6 TIMESTAMP,
        ATIMEON7 TIMESTAMP,
        ATIMEOFF7 TIMESTAMP,
        TIMECONTROL1 BIGINT,
        OBJPRIORITY1 BIGINT,
        PPKID BIGINT,
        ENG1 BIGINT,
        ENG2 BIGINT,
        ENG3 BIGINT,
        XOZORGID BIGINT,
        RESERVTEXT VARCHAR(102),
        RESERVLONG2 BIGINT,
        RESERVDATA1 TIMESTAMP,
        RESERVDATA2 TIMESTAMP,
        RESERVPHONE1 VARCHAR(42),
        RESERVPHONE2 VARCHAR(42),
        GSMPHONE VARCHAR(32),
        GSMACCOUNT TIMESTAMP,
        GSMHIDENINT BIGINT,
        OBJCHAN BIGINT,
        RESBYTE1 BIGINT,
        RESBIGINT1 BIGINT,
        RESBIGINT2 BIGINT,
        RESVARCHAR1 VARCHAR(102),
        RESVARCHAR2 VARCHAR(102),
        OBJCHAN2 BIGINT,
        RESBYTE2 BIGINT,
        ID_RISK_CATEGORY BIGINT,
        GSMPHONE2 VARCHAR(32),
        GUARDED_DAYS SMALLINT DEFAULT 255,
        SBSA VARCHAR(52),
        SBSB VARCHAR(52),
        NOVA_MF_CODE VARCHAR(20) DEFAULT '',
        CCTV SMALLINT DEFAULT 0,
        INSTALLER BIGINT DEFAULT 0,
        MANAGER BIGINT DEFAULT 0,
        EXTENDOBJ SMALLINT DEFAULT 0,
CONSTRAINT PK_OBJECTS_INFO PRIMARY KEY (OBJUIN));

/* Table: OBJECTS_LA, Owner: SYSDBA */
CREATE TABLE OBJECTS_LA (ID BIGINT NOT NULL,
        OBJUIN BIGINT,
        OBJN BIGINT,
        GRPN BIGINT,
        LASTTESTTIME1 TIMESTAMP,
        ISCONNSTATE1 BIGINT,
        LASTEVID BIGINT,
        LASTEVTIME1 TIMESTAMP,
        ISCONNSTATECHAN1 BIGINT,
        ISCONNSTATECHAN2 BIGINT,
        LASTACTTIME1 TIMESTAMP,
        LASTACTTIME2 TIMESTAMP,
CONSTRAINT PK_OBJECTS_LA PRIMARY KEY (ID));

/* Table: OBJECTS_STATE, Owner: SYSDBA */
CREATE TABLE OBJECTS_STATE (ID BIGINT NOT NULL,
        OBJUIN BIGINT,
        OBJN BIGINT,
        GRPN BIGINT,
        GUARDSTATE1 BIGINT,
        ALARMSTATE1 BIGINT,
        TECHALARMSTATE1 BIGINT,
        ISCONNSTATE1 BIGINT,
        LASTEVID BIGINT,
        LASTEVTIME1 TIMESTAMP,
        TESTCONTROL1 BIGINT,
        TESTTIME1 BIGINT,
        NEXTTESTTIME1 TIMESTAMP,
        LASTTESTTIME1 TIMESTAMP,
        GRPPERS BIGINT,
        OLDGRPPERS BIGINT,
        POWERFAULT BIGINT,
        RESERVLONG1 BIGINT,
        GSMFLATCODEINT BIGINT,
        OBJCHAN BIGINT,
        FCNEW BIGINT,
        FCOLD BIGINT,
        GPRS_IDPS SMALLINT,
        GPRS_IDPS_OLD SMALLINT,
        DAT0S SMALLINT,
        DAT1S SMALLINT,
        DAT0S_OLD SMALLINT,
        DAT1S_OLD SMALLINT,
        FCNEW2 BIGINT,
        FCOLD2 BIGINT,
        TESTCONTROL2 BIGINT,
        TESTTIME2 BIGINT,
        CURRENT_CHAN SMALLINT,
        LASTACTIVEGSMPHONE SMALLINT DEFAULT 0,
        USE_SET_AFTER_UNSET_CONTROL SMALLINT DEFAULT 0,
        USAUC_INTERVAL BIGINT DEFAULT 0,
        USAUC_UNSET_DT TIMESTAMP,
        USAUC_ALARM SMALLINT DEFAULT 0,
        ISZONEOFF SMALLINT DEFAULT 0 NOT NULL,
        AKBSTATE SMALLINT DEFAULT 0,
        TMPRALARM SMALLINT DEFAULT 0,
        BLOCKEDARMED_ON_OFF SMALLINT DEFAULT 0,
        TRKISCHECKING SMALLINT DEFAULT 0,
        TRKISCHECKINGDT TIMESTAMP,
        TRKISCHECKED SMALLINT DEFAULT 0,
        AON_ALARM SMALLINT DEFAULT 0,
        GSM_LEVEL SMALLINT DEFAULT 0,
        READBUFFFAULT SMALLINT DEFAULT 0,
        PSOFAILED SMALLINT DEFAULT 0,
        NTFSTATE SMALLINT DEFAULT 0,
CONSTRAINT PK_OBJECTS_STATE PRIMARY KEY (ID));

/* Table: OBJECTS_VINFO2, Owner: SYSDBA */
CREATE TABLE OBJECTS_VINFO2 (ID BIGINT NOT NULL,
        OBJUIN BIGINT,
        OBJN BIGINT,
        GRPN BIGINT,
        PPK_CODE SMALLINT DEFAULT 0,
        PPK_NAME VARCHAR(30),
        PPK_HWVERSION BIGINT,
        PPK_SOFTVERSION BIGINT,
        PPK_SOFTREVISION BIGINT,
        PPK_LDTGINFO TIMESTAMP,
CONSTRAINT PK_OBJECTS_VINFO2 PRIMARY KEY (ID));

/* Table: OBJREGS, Owner: SYSDBA */
CREATE TABLE OBJREGS (ID BIGINT NOT NULL,
        REG1 VARCHAR(102),
        RESBYTE1 BIGINT,
        REGINDTF VARCHAR(12),
CONSTRAINT PK_OBJREGS PRIMARY KEY (ID));

/* Table: OBJTYPES, Owner: SYSDBA */
CREATE TABLE OBJTYPES (ID BIGINT NOT NULL,
        OBJTYPE1 VARCHAR(62),
        RESBYTE1 BIGINT,
        BANK_OBJ_TYPE SMALLINT DEFAULT 0,
        BANK_MFO VARCHAR(20) DEFAULT '0',
CONSTRAINT PK_OBJTYPES PRIMARY KEY (ID));

/* Table: PCN_RINFO, Owner: SYSDBA */
CREATE TABLE PCN_RINFO (ID BIGINT,
        ORGNAME VARCHAR(250),
        COUNTRY BIGINT,
        REGION BIGINT,
        CITY BIGINT,
        ADDR VARCHAR(400),
        PCNNAME VARCHAR(250),
        PCN_TYPE SMALLINT);

/* Table: PERSONAL, Owner: SYSDBA */
CREATE TABLE PERSONAL (ID BIGINT NOT NULL,
        SURNAME1 VARCHAR(62),
        NAME1 VARCHAR(30),
        SECNAME1 VARCHAR(34),
        ADDRESS1 VARCHAR(202),
        PHONES1 VARCHAR(122),
        STATUS1 VARCHAR(62),
        ACCESS1 BIGINT,
        PASSW1 VARCHAR(22),
        BIRTHDAY1 TIMESTAMP,
        ORDER1 SMALLINT,
        NOTES1 VARCHAR(102),
        OBJUIN BIGINT,
        ISRANG BIGINT,
        RESBYTE1 BIGINT,
        GRPPERS BIGINT,
        LSTACT TIMESTAMP,
        PCONNECTED SMALLINT,
        LST_MESS_IND BIGINT,
        RECIPIENTSMS SMALLINT DEFAULT 0,
        SMS_LNG SMALLINT DEFAULT 0,
        SMS_MAX BIGINT DEFAULT 0,
        SMS_ALARM SMALLINT DEFAULT 1,
        SMS_TECHALARM SMALLINT DEFAULT 1,
        SMS_ARMING SMALLINT DEFAULT 1,
        SMS_OTHER SMALLINT DEFAULT 1,
        VIBER_ID VARCHAR(26),
        TELEGRAM_ID VARCHAR(20),
        REC_SMS SMALLINT DEFAULT 0,
        REC_VIBER SMALLINT DEFAULT 0,
        REC_TELEGRAM SMALLINT DEFAULT 0,
        HOGRP BIGINT,
        IT_AL SMALLINT DEFAULT 0,
CONSTRAINT PK_PERSONAL PRIMARY KEY (ID));

/* Table: PERS_INSTALLER, Owner: SYSDBA */
CREATE TABLE PERS_INSTALLER (ID BIGINT,
        SURNAME1 VARCHAR(62),
        NAME1 VARCHAR(30),
        SECNAME1 VARCHAR(34),
        PHONES1 VARCHAR(122),
        PHONES2 VARCHAR(122),
        PHONES3 VARCHAR(122),
        NOTES1 VARCHAR(202));

/* Table: PERS_MANAGER, Owner: SYSDBA */
CREATE TABLE PERS_MANAGER (ID BIGINT,
        SURNAME1 VARCHAR(62),
        NAME1 VARCHAR(30),
        SECNAME1 VARCHAR(34),
        PHONES1 VARCHAR(122),
        PHONES2 VARCHAR(122),
        PHONES3 VARCHAR(122),
        NOTES1 VARCHAR(202));

/* Table: PERS_REGISTERED, Owner: SYSDBA */
CREATE TABLE PERS_REGISTERED (ID BIGINT,
        SURNAME VARCHAR(62),
        NAME VARCHAR(30),
        SECONDNAME VARCHAR(34),
        PHONE1 VARCHAR(15),
        PHONE2 VARCHAR(15),
        PHONE3 VARCHAR(15),
        EMAIL VARCHAR(50),
        OTHER VARCHAR(50),
        PRS_TYPE SMALLINT);

/* Table: PPK, Owner: SYSDBA */
CREATE TABLE PPK (ID BIGINT NOT NULL,
        PANELMARK1 VARCHAR(52),
        PANELTYPE0 BIGINT,
        ZONESCOUNT1 BIGINT,
        RELAYCOUNT1 BIGINT,
        PGMCOUNT1 BIGINT,
        INCOUNT1 BIGINT,
        ASPTOUTCOUNT1 BIGINT,
        OPOVOUTCOUNT1 BIGINT,
        VENTOUTCOUNT1 BIGINT,
        CONTROLOUTCOUNT1 BIGINT,
        RESBYTE1 BIGINT,
CONSTRAINT PK_PPK PRIMARY KEY (ID));

/* Table: PRSGROUP, Owner: SYSDBA */
CREATE TABLE PRSGROUP (ID BIGINT NOT NULL,
        GRPNUM BIGINT,
        INFO VARCHAR(102),
        NOTES1 VARCHAR(102),
        IPADDRESS VARCHAR(102),
        LASTACT TIMESTAMP,
        CURRUSER BIGINT,
        RESBIGINT1 BIGINT,
        RESBIGINT2 BIGINT,
        RESVARCHAR1 VARCHAR(102),
        RESVARCHAR2 VARCHAR(102),
CONSTRAINT PK_PRSGROUP PRIMARY KEY (ID));

/* Table: PULT_INFO, Owner: SYSDBA */
CREATE TABLE PULT_INFO (ID BIGINT,
        PARAM_NAME VARCHAR(20),
        PARAM_VALUE VARCHAR(100));

/* Table: RADIO_PPK, Owner: SYSDBA */
CREATE TABLE RADIO_PPK (R_N_ID DOM_N_ID,
        R_X DOM_INTEGER,
        R_Y DOM_INTEGER,
        R_NUM_OBJECT DOM_N_ID,
        R_WINDOW_VALIDATE DOM_BYTE,
        R_STATUS DOM_BYTE,
        R_COUNT_MINUTE DOM_BYTE,
        R_MAX_COUNT_MINUTE DOM_BYTE,
        R_ADRESS1 DOM_INTEGER,
        R_ADRESS2 DOM_INTEGER,
        R_ADRESS3 DOM_INTEGER,
        R_ADRESS4 DOM_INTEGER,
        R_LEVEL1 DOM_BYTE,
        R_LEVEL2 DOM_BYTE,
        R_LEVEL3 DOM_BYTE,
        R_LEVEL4 DOM_BYTE,
        R_CURRENT_ADRESS DOM_INTEGER,
        R_CURRENT_LEVEL DOM_BYTE,
        R_COUNT_CONNECT_REAL DOM_INTEGER,
        R_COUNT_CONNECT_OUTSIDE DOM_INTEGER,
        R_HIDE_NUM_PPK DOM_INTEGER,
        R_FLOAT_CODE_OUTSIDE DOM_INTEGER,
        R_IS_RETR DOM_BYTE DEFAULT 0,
        R_COUNT_ADRESS DOM_BYTE DEFAULT 1 NOT NULL,
CONSTRAINT PK_RADIO_PPK PRIMARY KEY (R_N_ID));

/* Table: SBS, Owner: SYSDBA */
CREATE TABLE SBS (ID BIGINT NOT NULL,
        SBINFO VARCHAR(100),
        SBIND VARCHAR(52),
        SBHOST VARCHAR(50),
        SBPDB VARCHAR(120),
        SBTYPE SMALLINT,
        SBHOST2 VARCHAR(50) DEFAULT '',
CONSTRAINT PK_SBS PRIMARY KEY (ID));

/* Table: SBS_ACTIV, Owner: SYSDBA */
CREATE TABLE SBS_ACTIV (ID BIGINT NOT NULL,
        SBIND VARCHAR(52),
        SBLATIME TIMESTAMP,
        STATE_TA SMALLINT DEFAULT 0,
CONSTRAINT PK_SBS_ACTIV PRIMARY KEY (ID));

/* Table: SBS_PORT, Owner: SYSDBA */
CREATE TABLE SBS_PORT (ID BIGINT NOT NULL,
        SBIND VARCHAR(52),
        SBPORTPARAM VARCHAR(72),
CONSTRAINT PK_SBS_PORT PRIMARY KEY (ID));

/* Table: SMS_MESS, Owner: SYSDBA */
CREATE TABLE SMS_MESS (ID BIGINT,
        EVUIN BIGINT,
        SMSID BIGINT);

/* Table: SMS_TEXT, Owner: SYSDBA */
CREATE TABLE SMS_TEXT (ID BIGINT,
        MESS_EN VARCHAR(70),
        MESS_UA VARCHAR(70),
        MESS_RU VARCHAR(70),
        MESS_OL VARCHAR(70));

/* Table: SOFT_VER, Owner: SYSDBA */
CREATE TABLE SOFT_VER (ID BIGINT,
        EXENAME VARCHAR(20),
        PCHOST VARCHAR(50),
        VERSION VARCHAR(12),
        BUILD VARCHAR(12),
        REVISION VARCHAR(12),
        SBSIND VARCHAR(52),
        SBSTYPE SMALLINT,
        MAX_MAJV BIGINT,
        MAX_MINV BIGINT,
        MAX_REL BIGINT,
        MAX_BUILD BIGINT);

/* Table: SRVLSTACT, Owner: SYSDBA */
CREATE TABLE SRVLSTACT (LSTACTTIME1 TIMESTAMP,
        RESBYTE1 BIGINT,
        RESBIGINT1 BIGINT,
        RESBIGINT2 BIGINT,
        RESVARCHAR1 VARCHAR(102),
        RESVARCHAR2 VARCHAR(102));

/* Table: TAREP, Owner: SYSDBA */
CREATE TABLE TAREP (ID BIGINT NOT NULL,
        OBJN BIGINT,
        OBJSHORTNAME1 VARCHAR(102),
        ADDRESS1 VARCHAR(202),
        INFORMED VARCHAR(202),
        DT_ALARM TIMESTAMP,
        DT_INFORMED TIMESTAMP,
CONSTRAINT PK_TAREP PRIMARY KEY (ID));

/* Table: TFORALARMSREPORT, Owner: SYSDBA */
CREATE TABLE TFORALARMSREPORT (OBJN BIGINT NOT NULL,
        OBJFULLNAME VARCHAR(202),
        EVTIME TIMESTAMP,
        TIMEVGZ TIMESTAMP,
        TIMEPGZ TIMESTAMP,
        ROSM VARCHAR(202),
        PMERY VARCHAR(202),
        RESBYTE BIGINT,
        RESSTR1 VARCHAR(202),
        RESSTR2 VARCHAR(202),
        RESDC1 BIGINT,
        RESDC2 BIGINT);

/* Table: UR_PARAMS, Owner: SYSDBA */
CREATE TABLE UR_PARAMS (ID BIGINT,
        USERID BIGINT,
        PARAM_NAME VARCHAR(20),
        PARAM_VALUE SMALLINT);

/* Table: USERSTATUS, Owner: SYSDBA */
CREATE TABLE USERSTATUS (USERNAME VARCHAR(135),
        USERTYPE SMALLINT,
        GROUPNAME VARCHAR(102),
        USERSTATE SMALLINT);

/* Table: XOZORG, Owner: SYSDBA */
CREATE TABLE XOZORG (ID BIGINT NOT NULL,
        SHORTNAME1 VARCHAR(102),
        FULLNAME1 VARCHAR(202),
        ADDRESS1 VARCHAR(202),
        PHONES1 VARCHAR(202),
        NOTES1 VARCHAR(512),
        RESBYTE1 BIGINT,
CONSTRAINT PK_XOZORG PRIMARY KEY (ID));

/* Table: ZONES, Owner: SYSDBA */
CREATE TABLE ZONES (ID BIGINT NOT NULL,
        OBJUIN BIGINT,
        OBJN BIGINT,
        GRPN BIGINT,
        ZONEN BIGINT,
        ZONESTATE1 BIGINT,
        ZONETYPE1 BIGINT,
        ZONEDESCR1 VARCHAR(202),
        ALARMSTATE1 BIGINT,
        TIMECTRL1 TIMESTAMP,
        TIMECTRL2 TIMESTAMP,
        RESBIGINT1 BIGINT,
        RESBIGINT2 BIGINT,
        RESVARCHAR1 VARCHAR(102),
        RESVARCHAR2 VARCHAR(102),
        ZONEON SMALLINT DEFAULT 1 NOT NULL,
        TECHALARMSTATE1 SMALLINT,
        ZNGRP BIGINT,
CONSTRAINT PK_ZONES PRIMARY KEY (ID));

/*  External Function declarations */
DECLARE EXTERNAL FUNCTION USTRUPPERCASE
CSTRING(512) CHARACTER SET WIN1251
RETURNS CSTRING(512) CHARACTER SET WIN1251 FREE_IT
ENTRY_POINT 'StrUpperCase' MODULE_NAME 'MOST5_UDF.dll';


COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;

/* Stored procedures headers */
CREATE OR ALTER PROCEDURE CHECK_POST_EVENT AS 
BEGIN SUSPEND; END ^
CREATE OR ALTER PROCEDURE MESS_CHANGE_OBJECT AS 
BEGIN EXIT; END ^
CREATE OR ALTER PROCEDURE MESS_CHANGE_RADIOPOINT AS 
BEGIN EXIT; END ^
CREATE OR ALTER PROCEDURE SETLTANDISCONN (GET_OBJN BIGINT)
AS 
BEGIN EXIT; END ^

SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;

/*  Index definitions for all user tables */
CREATE UNIQUE INDEX INDEX_ACTALARMS ON ACTALARMS (ID);
CREATE UNIQUE INDEX INDEX_ALARMREAS ON ALARMREAS (ID);
CREATE UNIQUE INDEX INDEX_ECS ON ECS (ID);
CREATE UNIQUE INDEX INDEX_EVLOG ON EVLOG (ID);
CREATE UNIQUE INDEX PRIMARYKEY ON GLOBALCFG (ID);
CREATE UNIQUE INDEX INDEX_GPS_SRV ON GPS_SRV (ID);
CREATE UNIQUE INDEX INDEX_GUARD_GROUPS ON GUARD_GROUPS (ID);
CREATE UNIQUE INDEX INDEX_HARDLOG ON HARDLOG (ID);
CREATE UNIQUE INDEX INDEX_IMAGES ON IMAGES (ID);
CREATE UNIQUE INDEX INDEX_JOURNAL ON JOURNAL (ID);
CREATE UNIQUE INDEX INDEX_MESSLIST ON MESSLIST (UIN);
CREATE UNIQUE INDEX INDEX_OBJECTS ON OBJECTS (OBJUIN);
CREATE UNIQUE INDEX INDEX_OBJECTS_GPS ON OBJECTS_GPS (ID);
CREATE UNIQUE INDEX INDEX_OBJECTS_INFO ON OBJECTS_INFO (OBJUIN);
CREATE UNIQUE INDEX INDEX_OBJECTS_LA ON OBJECTS_LA (ID);
CREATE UNIQUE INDEX INDEX_OBJECTS_STATE ON OBJECTS_STATE (ID);
CREATE UNIQUE INDEX INDEX_OBJECTS_VINFO2 ON OBJECTS_VINFO2 (ID);
CREATE UNIQUE INDEX INDEX_OBJREGS ON OBJREGS (ID);
CREATE UNIQUE INDEX INDEX_OBJTYPES ON OBJTYPES (ID);
CREATE UNIQUE INDEX INDEX_PERSONAL ON PERSONAL (ID);
CREATE UNIQUE INDEX INDEX_PERS_INSTALLER ON PERS_INSTALLER (ID);
CREATE UNIQUE INDEX INDEX_PERS_MANAGER ON PERS_MANAGER (ID);
CREATE UNIQUE INDEX INDEX_PPK ON PPK (ID);
CREATE UNIQUE INDEX INDEX_PRSGROUP ON PRSGROUP (ID);
CREATE UNIQUE INDEX INDEX_PULT_INFO ON PULT_INFO (ID);
CREATE UNIQUE INDEX INDEX_SBS ON SBS (ID);
CREATE UNIQUE INDEX INDEX_SBS_ACTIV ON SBS_ACTIV (ID);
CREATE UNIQUE INDEX INDEX_SBS_PORT ON SBS_PORT (ID);
CREATE UNIQUE INDEX INDEX_SMS_MESS ON SMS_MESS (ID);
CREATE UNIQUE INDEX INDEX_SMS_TEXT ON SMS_TEXT (ID);
CREATE UNIQUE INDEX INDEX_UR_PARAMS ON UR_PARAMS (ID);
CREATE UNIQUE INDEX INDEX_XOZORG ON XOZORG (ID);
CREATE UNIQUE INDEX INDEX_ZONES ON ZONES (ID);

ALTER TABLE FP_EVENTS ADD CONSTRAINT FK_FP_EVENTS_1 FOREIGN KEY (FP_TYPE) REFERENCES FP_TYPE_EVENT (TE_N_ID) ON UPDATE CASCADE ON DELETE CASCADE;

COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;

/* Stored procedures bodies */

ALTER PROCEDURE CHECK_POST_EVENT AS 
begin
POST_EVENT 'check_post_event';
suspend;
end ^

ALTER PROCEDURE MESS_CHANGE_OBJECT AS 
 begin post_event 'CHANGE_OBJECT'; end ^

ALTER PROCEDURE MESS_CHANGE_RADIOPOINT AS 
 begin post_event 'CHANGE_RADIOPOINTS'; end ^

ALTER PROCEDURE SETLTANDISCONN (GET_OBJN BIGINT)
AS 
begin
  UPDATE OBJECTS SET IsConnState1=1,LastTestTime1=current_timestamp WHERE ObjN=:get_objn;
end ^

SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;
SET TERM ^ ;

/* Triggers only will work for SQL triggers */
CREATE TRIGGER AI_ACTALARMS FOR ACTALARMS 
ACTIVE BEFORE INSERT POSITION 0 
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID=GEN_ID(GEN_FOR_AI_ACTALARMS,1); END ^

CREATE TRIGGER ALADDINFO2 FOR ACTALARMS 
ACTIVE BEFORE INSERT POSITION 0 
AS

declare GINFOSTR char(250);

begin

if (NEW.SCENERYID in (1,16)) then

begin

GINFOSTR=NEW.INFO1||' '||(select first 1 ZONEDESCR1 from ZONES where ((ZONES.OBJUIN=NEW.OBJUIN) and (new.ZONEN=ZONES.ZONEN)

and (ZONES.ZONEDESCR1<>'')));

if(GINFOSTR='')then

begin

GINFOSTR='[]';

end

else

if(char_length(GINFOSTR)>202)then

begin

GINFOSTR=substring(GINFOSTR from 1 for 202);

end

if (GINFOSTR is null) then

begin

new.INFO1=NEW.INFO1;

end

else

begin

new.INFO1=GINFOSTR;

end

end

end
 ^

CREATE TRIGGER AALARMS_EV_INSERTED FOR ACTALARMS 
ACTIVE AFTER INSERT POSITION 0 
AS DECLARE EVENT_NAME VARCHAR(100); 
DECLARE REMOTE_OID INT; 
begin EVENT_NAME ='actalarm_inserted'; 
POST_EVENT EVENT_NAME; 
if (new.sceneryid = 1) then insert into fp_events (FP_DATE, FP_TYPE, FP_INFO, 
FP_NUMBER_OBJECT, FP_NUMBER_GROUP, FP_NUMBER_ZONE, ADDINFO, ARRIVALTIME,ALARMID,ALARMSTATE) 
values (current_timestamp, 3, 'Fire', new.objn, new.grpn, new.zonen, new.INFO1, new.EVTIME1, new.ID, 0);  end ^

CREATE TRIGGER ACTALARMS_EV_UPDATED FOR ACTALARMS 
ACTIVE AFTER UPDATE POSITION 0 
AS
DECLARE EVENT_NAME VARCHAR(100);
DECLARE REMOTE_OID INT;
begin
EVENT_NAME ='actalarm_updated';
POST_EVENT EVENT_NAME;
end ^

CREATE TRIGGER ACTALARMS_EV_DELETED FOR ACTALARMS 
ACTIVE AFTER DELETE POSITION 0 
AS
DECLARE EVENT_NAME VARCHAR(100);
DECLARE REMOTE_OID INT;
begin
EVENT_NAME ='actalarm_deleted';
POST_EVENT EVENT_NAME;
end ^

CREATE TRIGGER AI_ALARMREAS FOR ALARMREAS 
ACTIVE BEFORE INSERT POSITION 0 
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID=GEN_ID(GEN_FOR_AI_ALARMREAS,1); END ^

CREATE TRIGGER ALLCHANGES_AI0 FOR ALLCHANGES 
ACTIVE AFTER INSERT POSITION 0 
AS DECLARE VARIABLE EVENT_NAME VARCHAR(100); BEGIN EVENT_NAME = 'changed_base'; POST_EVENT EVENT_NAME; END ^

CREATE TRIGGER AI_AREP FOR AREP 
ACTIVE BEFORE INSERT POSITION 0 
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID=GEN_ID(GEN_FOR_AI_AREP,1); END ^

CREATE TRIGGER CPTS_CHAN_AI FOR CPTS_CHAN 
ACTIVE BEFORE INSERT POSITION 0 
as 
begin 
if (new.id is null) then 
new.id = gen_id(GEN_FOR_AI_CPTS_CHAN,1); 
end ^

CREATE TRIGGER CPTS_INFO_AI FOR CPTS_INFO 
ACTIVE BEFORE INSERT POSITION 0 
as 
begin 
if (new.id is null) then 
new.id = gen_id(GEN_FOR_AI_CPTS_INFO,1); 
end ^

CREATE TRIGGER CPTS_OBJ_INFO_AI FOR CPTS_OBJ_INFO 
ACTIVE BEFORE INSERT POSITION 0 
as 
begin 
if (new.id is null) then 
new.id = gen_id(GEN_FOR_AI_CPTS_OBJ_INFO,1); 
end ^

CREATE TRIGGER CPTS_PERSONAL_AI FOR CPTS_PERSONAL 
ACTIVE BEFORE INSERT POSITION 0 
as 
begin 
if (new.id is null) then 
new.id = gen_id(GEN_FOR_AI_CPTS_PERSONAL,1); 
end ^

CREATE TRIGGER AI_DCT_CITY FOR DCT_CITY 
ACTIVE BEFORE INSERT POSITION 0 
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID=GEN_ID(gen_dct_city,1); END ^

CREATE TRIGGER AI_DCT_CNTR FOR DCT_COUNTRY 
ACTIVE BEFORE INSERT POSITION 0 
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID=GEN_ID(gen_dct_cntr,1); END ^

CREATE TRIGGER AI_DCT_RG FOR DCT_REGION 
ACTIVE BEFORE INSERT POSITION 0 
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID=GEN_ID(gen_dct_rg,1); END ^

CREATE TRIGGER AI_DELREAS FOR DELREAS 
ACTIVE BEFORE INSERT POSITION 0 
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID=GEN_ID(GEN_FOR_AI_DELREAS,1); END ^

CREATE TRIGGER AI_DELREPORT FOR DELREPORT 
ACTIVE BEFORE INSERT POSITION 0 
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID=GEN_ID(GEN_FOR_AI_DELREPORT,1); END ^

CREATE TRIGGER AI_ECS FOR ECS 
ACTIVE BEFORE INSERT POSITION 0 
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID=GEN_ID(GEN_FOR_AI_ECS,1); END ^

CREATE TRIGGER AI_EVLOG FOR EVLOG 
ACTIVE BEFORE INSERT POSITION 0 
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID=GEN_ID(GEN_FOR_AI_EVLOG,1); END ^

CREATE TRIGGER EVLADDINF2 FOR EVLOG 
ACTIVE BEFORE INSERT POSITION 0 
AS

declare GINFOSTR char(250);

declare GETEVUIN bigint;

declare GETXO    char(150);

begin

GETEVUIN=NEW.EVUIN;

if (exists(select messlist.sc1 from messlist where messlist.UIN=:GETEVUIN and messlist.sc1 in (1,16))) then

begin

GINFOSTR=NEW.INFO1||' '||(select first 1 ZONEDESCR1 from ZONES where ((ZONES.OBJUIN=NEW.OBJUIN) and (new.ZONEN=ZONES.ZONEN)

and (ZONES.ZONEDESCR1<>'')));

if(GINFOSTR='')then

begin

GINFOSTR='[]';

end

else

if(char_length(GINFOSTR)>202)then

begin

GINFOSTR=substring(GINFOSTR from 1 for 202);

end

if(GINFOSTR is null)then

begin

new.INFO1=NEW.INFO1;

end

else

begin

new.INFO1=GINFOSTR;

end

end

if(NEW.XONUM>0)then

begin

if (exists(select messlist.sc1 from messlist where messlist.UIN=:GETEVUIN and messlist.sc1 in (3,4,10,11))) then

begin

GETXO=(select first 1 trim(cast(SurName1 as char(62)))||' '||trim(cast(Name1 as char(30)))||' '||trim(cast(SecName1 as char(34))) from PERSONAL where

((PERSONAL.OBJUIN=NEW.OBJUIN) and (new.XONUM=PERSONAL.ORDER1)));

if(GETXO is null)then GETXO='#'||cast(new.XONUM as char(3));

GINFOSTR=NEW.INFO1||' X/o '||GETXO;

if(GINFOSTR='[]')then

begin

GINFOSTR='';

end

else

if(char_length(GINFOSTR)>202)then

begin

GINFOSTR=substring(GINFOSTR from 1 for 202);

end

if(GINFOSTR is null) then

begin

new.INFO1=NEW.INFO1;

end

else

begin

new.INFO1=GINFOSTR;

end

end

end

end
 ^

CREATE TRIGGER EVLOG_EV_CHANGED FOR EVLOG 
ACTIVE AFTER INSERT POSITION 0 
AS
DECLARE EVENT_NAME VARCHAR(100);
DECLARE REMOTE_OID INT;
begin
EVENT_NAME ='evlog_changed';
POST_EVENT EVENT_NAME;
end ^

CREATE TRIGGER EV_INSERTED_FOR_L FOR EVLOG 
INACTIVE AFTER INSERT POSITION 0 
AS 

begin 

INSERT INTO EVLOG_TMP(ID,EVTIME1,OBJUIN,GRPN,ZONEN,EVUIN,INFO1) VALUES (NEW.ID,NEW.EVTIME1,NEW.OBJUIN,NEW.GRPN,NEW.ZONEN,NEW.EVUIN,NEW.INFO1); 

end ^

CREATE TRIGGER TR_EVLOG_AI FOR EVLOG 
ACTIVE AFTER INSERT POSITION 0 
AS
DECLARE EVENT_NAME VARCHAR(100);
DECLARE REMOTE_OID INT;
begin
EVENT_NAME ='new_evlog_item';
IF (104 = NEW.EVUIN)
THEN BEGIN
POST_EVENT EVENT_NAME;
END
end ^

CREATE TRIGGER AI_FIXREAS FOR FIXREAS 
ACTIVE BEFORE INSERT POSITION 0 
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID=GEN_ID(GEN_FOR_AI_FIXREAS,1); END ^

CREATE TRIGGER AI_FIXREPORT FOR FIXREPORT 
ACTIVE BEFORE INSERT POSITION 0 
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID=GEN_ID(GEN_FOR_AI_FIXREPORT,1); END ^

CREATE TRIGGER FP_EVENTS_BI FOR FP_EVENTS 
ACTIVE BEFORE INSERT POSITION 0 
AS BEGIN IF (NEW.FP_N_ID IS NULL) THEN NEW.FP_N_ID = GEN_ID(GEN_FP_EVENTS_ID,1); END ^

CREATE TRIGGER FP_EVENTS_AI0 FOR FP_EVENTS 
ACTIVE AFTER INSERT POSITION 0 
AS begin POST_EVENT 'new_fp_events_item'; end ^

CREATE TRIGGER FP_TYPE_EVENT_BI FOR FP_TYPE_EVENT 
ACTIVE BEFORE INSERT POSITION 0 
AS BEGIN IF (NEW.TE_N_ID IS NULL) THEN NEW.TE_N_ID = GEN_ID(GEN_FP_TYPE_EVENT_ID,1); END ^

CREATE TRIGGER AI_GLOBALCFG FOR GLOBALCFG 
ACTIVE BEFORE INSERT POSITION 0 
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID=GEN_ID(GEN_FOR_AI_GLOBALCFG,1); END ^

CREATE TRIGGER GPRSCFG_EV_CHANGED FOR GPRSCFG 
ACTIVE AFTER UPDATE POSITION 0 
AS
DECLARE EVENT_NAME_TRUE  VARCHAR(100);
DECLARE EVENT_NAME_FALSE VARCHAR(100);
begin
EVENT_NAME_TRUE ='gprs_use_com_port_true';
EVENT_NAME_FALSE ='gprs_use_com_port_false';
if (new.usecomport=1) then POST_EVENT event_name_true;
                      else POST_EVENT event_name_false;
end ^

CREATE TRIGGER AI_GPS_SRV FOR GPS_SRV 
ACTIVE BEFORE INSERT POSITION 0 
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID=GEN_ID(GEN_FOR_AI_GPS_SRV,1); END ^

CREATE TRIGGER GRPZN_BI FOR GRPZN 
ACTIVE BEFORE INSERT POSITION 0 
as 
begin 
if (new.id is null) then 
new.id = gen_id(gen_grpzn_id,1); 
end ^

CREATE TRIGGER GRP_ECS_AI FOR GRP_ECS 
ACTIVE BEFORE INSERT POSITION 0 
as 
begin 
if (new.id is null) then 
new.id = gen_id(GEN_FOR_AI_GRP_ECS,1); 
end ^

CREATE TRIGGER AI_GUARD_GROUPS FOR GUARD_GROUPS 
ACTIVE BEFORE INSERT POSITION 0 
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID=GEN_ID(GEN_FOR_AI_GUARD_GROUPS,1); END ^

CREATE TRIGGER AI_HARDLOG FOR HARDLOG 
ACTIVE BEFORE INSERT POSITION 0 
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID=GEN_ID(GEN_FOR_AI_HARDLOG,1); END ^

CREATE TRIGGER AI_IMAGES FOR IMAGES 
ACTIVE BEFORE INSERT POSITION 0 
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID=GEN_ID(GEN_FOR_AI_IMAGES,1); END ^

CREATE TRIGGER AI_JOURNAL FOR JOURNAL 
ACTIVE BEFORE INSERT POSITION 0 
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID=GEN_ID(GEN_FOR_AI_JOURNAL,1); END ^

CREATE TRIGGER LOGSCONTROL_CHANGED FOR LOGSCONTROL 
ACTIVE AFTER UPDATE POSITION 0 
AS
begin
POST_EVENT 'LC_CHANGED';
end ^

CREATE TRIGGER AI_MAINFO FOR MAINFO 
ACTIVE BEFORE INSERT POSITION 0 
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID=GEN_ID(GEN_AI_MAINFO,1); END ^

CREATE TRIGGER AI_MESSLIST FOR MESSLIST 
ACTIVE BEFORE INSERT POSITION 0 
AS BEGIN IF (NEW.UIN IS NULL) THEN NEW.UIN=GEN_ID(GEN_FOR_AI_MESSLIST,1); END ^

CREATE TRIGGER MESSLIST_EV_CHANGED FOR MESSLIST 
ACTIVE AFTER UPDATE POSITION 0 
AS
DECLARE EVENT_NAME VARCHAR(100);
begin
EVENT_NAME ='messlist_changed';
POST_EVENT EVENT_NAME;
end ^

CREATE TRIGGER AI_OBJECTS FOR OBJECTS 
ACTIVE BEFORE INSERT POSITION 0 
AS BEGIN IF (NEW.OBJUIN IS NULL) THEN NEW.OBJUIN=GEN_ID(GEN_FOR_AI_OBJECTS,1); END ^

CREATE TRIGGER OBJECTS_EV_INSERTED FOR OBJECTS 
ACTIVE AFTER INSERT POSITION 0 
AS
DECLARE EVENT_NAME VARCHAR(100);
DECLARE REMOTE_OID INT;
begin
EVENT_NAME ='objects_changed_inserted';
POST_EVENT EVENT_NAME;
end ^

CREATE TRIGGER OBJECTS_EV_UPDATED FOR OBJECTS 
ACTIVE AFTER UPDATE POSITION 0 
AS
DECLARE EVENT_NAME VARCHAR(100);
DECLARE REMOTE_OID INT;
DECLARE CHECKSTATENEW smallint;   /* 29.06.2012 */
begin
CHECKSTATENEW=0;
IF(NEW.GRPN<>OLD.GRPN) THEN
BEGIN
  CHECKSTATENEW=CHECKSTATENEW+1;
END
IF(NEW.OBJFULLNAME1<>OLD.OBJFULLNAME1) THEN
BEGIN
  CHECKSTATENEW=CHECKSTATENEW+1;
END
IF(NEW.OBJSHORTNAME1<>OLD.OBJSHORTNAME1) THEN
BEGIN
  CHECKSTATENEW=CHECKSTATENEW+1;
END
IF(NEW.GUARDSTATE1<>OLD.GUARDSTATE1) THEN
BEGIN
  CHECKSTATENEW=CHECKSTATENEW+1;
END
IF(NEW.ALARMSTATE1<>OLD.ALARMSTATE1) THEN
BEGIN
  CHECKSTATENEW=CHECKSTATENEW+1;
END
IF(NEW.TECHALARMSTATE1<>OLD.TECHALARMSTATE1) THEN
BEGIN
  CHECKSTATENEW=CHECKSTATENEW+1;
END
IF(NEW.OBJPRIORITY1<>OLD.OBJPRIORITY1) THEN
BEGIN
  CHECKSTATENEW=CHECKSTATENEW+1;
END
IF(NEW.PPKID<>OLD.PPKID) THEN
BEGIN
  CHECKSTATENEW=CHECKSTATENEW+1;
END
IF(NEW.ENG1<>OLD.ENG1) THEN
BEGIN
  CHECKSTATENEW=CHECKSTATENEW+1;
END
IF(NEW.ENG2<>OLD.ENG2) THEN
BEGIN
  CHECKSTATENEW=CHECKSTATENEW+1;
END
IF(NEW.ENG3<>OLD.ENG3) THEN
BEGIN
  CHECKSTATENEW=CHECKSTATENEW+1;
END
IF(NEW.RESERVLONG1<>OLD.RESERVLONG1) THEN
BEGIN
  CHECKSTATENEW=CHECKSTATENEW+1;
END
IF(NEW.RESERVLONG2<>OLD.RESERVLONG2) THEN
BEGIN
  CHECKSTATENEW=CHECKSTATENEW+1;
END
IF(NEW.OBJCHAN<>OLD.OBJCHAN) THEN
BEGIN
  CHECKSTATENEW=CHECKSTATENEW+1;
END
IF(NEW.RESBYTE1<>OLD.RESBYTE1) THEN
BEGIN
  CHECKSTATENEW=CHECKSTATENEW+1;
END
IF(NEW.GRPPERS<>OLD.GRPPERS) THEN
BEGIN
  CHECKSTATENEW=CHECKSTATENEW+1;
END
IF(NEW.OLDGRPPERS<>OLD.OLDGRPPERS) THEN
BEGIN
  CHECKSTATENEW=CHECKSTATENEW+1;
END
IF(NEW.POWERFAULT<>OLD.POWERFAULT) THEN
BEGIN
  CHECKSTATENEW=CHECKSTATENEW+1;
END
IF(NEW.RESBIGINT1<>OLD.RESBIGINT1) THEN
BEGIN
  CHECKSTATENEW=CHECKSTATENEW+1;
END
IF(NEW.RESBIGINT2<>OLD.RESBIGINT2) THEN
BEGIN
  CHECKSTATENEW=CHECKSTATENEW+1;
END
IF(NEW.OBJCHAN2<>OLD.OBJCHAN2) THEN
BEGIN
  CHECKSTATENEW=CHECKSTATENEW+1;
END
IF(NEW.RESBYTE2<>OLD.RESBYTE2) THEN
BEGIN
  CHECKSTATENEW=CHECKSTATENEW+1;
END
IF(NEW.RESBYTE2<>OLD.RESBYTE2) THEN
BEGIN
  CHECKSTATENEW=CHECKSTATENEW+1;
END
IF(NEW.CURRENT_CHAN<>OLD.CURRENT_CHAN) THEN
BEGIN
  CHECKSTATENEW=CHECKSTATENEW+1;
END
IF(CHECKSTATENEW>0)THEN
BEGIN
 EVENT_NAME ='objects_changed_updated';
 POST_EVENT EVENT_NAME;
END
end ^

CREATE TRIGGER OBJECTS_INFO_EV_UPDATED FOR OBJECTS 
ACTIVE AFTER UPDATE POSITION 0 
AS

DECLARE EVENT_NAME VARCHAR(100);

DECLARE REMOTE_OID INT;

DECLARE CHECKSTATE smallint;   /* 29.06.2012 */

begin

CHECKSTATE=0;

IF(NEW.GRPN<>OLD.GRPN) THEN

BEGIN

  CHECKSTATE=CHECKSTATE+1;

END

IF(NEW.OBJFULLNAME1<>OLD.OBJFULLNAME1) THEN

BEGIN

  CHECKSTATE=CHECKSTATE+1;

END

IF(NEW.OBJSHORTNAME1<>OLD.OBJSHORTNAME1) THEN

BEGIN

  CHECKSTATE=CHECKSTATE+1;

END

IF(NEW.OBJPRIORITY1<>OLD.OBJPRIORITY1) THEN

BEGIN

  CHECKSTATE=CHECKSTATE+1;

END

IF(NEW.PPKID<>OLD.PPKID) THEN

BEGIN

  CHECKSTATE=CHECKSTATE+1;

END

IF(NEW.ENG1<>OLD.ENG1) THEN

BEGIN

  CHECKSTATE=CHECKSTATE+1;

END

IF(NEW.ENG2<>OLD.ENG2) THEN

BEGIN

  CHECKSTATE=CHECKSTATE+1;

END

IF(NEW.ENG3<>OLD.ENG3) THEN

BEGIN

  CHECKSTATE=CHECKSTATE+1;

END

IF(NEW.RESERVLONG2<>OLD.RESERVLONG2) THEN

BEGIN

  CHECKSTATE=CHECKSTATE+1;

END

IF(NEW.OBJCHAN<>OLD.OBJCHAN) THEN

BEGIN

  CHECKSTATE=CHECKSTATE+1;

END

IF(NEW.RESBYTE1<>OLD.RESBYTE1) THEN

BEGIN

  CHECKSTATE=CHECKSTATE+1;

END

IF(NEW.RESBIGINT1<>OLD.RESBIGINT1) THEN

BEGIN

  CHECKSTATE=CHECKSTATE+1;

END

IF(NEW.RESBIGINT2<>OLD.RESBIGINT2) THEN

BEGIN

  CHECKSTATE=CHECKSTATE+1;

END

IF(NEW.OBJCHAN2<>OLD.OBJCHAN2) THEN

BEGIN

  CHECKSTATE=CHECKSTATE+1;

END

IF(NEW.RESBYTE2<>OLD.RESBYTE2) THEN

BEGIN

  CHECKSTATE=CHECKSTATE+1;

END

IF(CHECKSTATE>0)THEN

BEGIN

 EVENT_NAME ='OBJECTS_changed';

 POST_EVENT EVENT_NAME;

END

end ^

CREATE TRIGGER OBJECTS_EV_DELETED FOR OBJECTS 
ACTIVE AFTER DELETE POSITION 0 
AS
DECLARE EVENT_NAME VARCHAR(100);
DECLARE REMOTE_OID INT;
begin
EVENT_NAME ='objects_changed_deleted';
POST_EVENT EVENT_NAME;
end ^

CREATE TRIGGER AI_OBJECTS_GPS FOR OBJECTS_GPS 
ACTIVE BEFORE INSERT POSITION 0 
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID=GEN_ID(GEN_FOR_AI_OBJECTS_GPS,1); END ^

CREATE TRIGGER AI_OBJECTS_INFO FOR OBJECTS_INFO 
ACTIVE BEFORE INSERT POSITION 0 
AS BEGIN IF (NEW.OBJUIN IS NULL) THEN NEW.OBJUIN=GEN_ID(GEN_FOR_AI_OBJECTS_INFO,1); END ^

CREATE TRIGGER OBJECTS_INFO_EV_INSERTED FOR OBJECTS_INFO 
ACTIVE AFTER INSERT POSITION 0 
AS

DECLARE EVENT_NAME VARCHAR(100);

DECLARE REMOTE_OID INT;

begin

EVENT_NAME ='OBJECTS_inserted';

POST_EVENT EVENT_NAME;

end ^

CREATE TRIGGER OBJECTS_INFO_EV_DELETED FOR OBJECTS_INFO 
ACTIVE AFTER DELETE POSITION 0 
AS

DECLARE EVENT_NAME VARCHAR(100);

DECLARE REMOTE_OID INT;

begin

EVENT_NAME ='OBJECTS_deleted';

POST_EVENT EVENT_NAME;

end ^

CREATE TRIGGER AI_OBJECTS_LA FOR OBJECTS_LA 
ACTIVE BEFORE INSERT POSITION 0 
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID=GEN_ID(GEN_FOR_AI_OBJECTS_LA,1); END ^

CREATE TRIGGER AI_OBJECTS_STATE FOR OBJECTS_STATE 
ACTIVE BEFORE INSERT POSITION 0 
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID=GEN_ID(GEN_FOR_AI_OBJECTS_STATE,1); END ^

CREATE TRIGGER AUTO_CA220 FOR OBJECTS_STATE 
ACTIVE BEFORE UPDATE POSITION 0 
AS

declare GETALARMRC bigint;

begin

if ((old.POWERFAULT=1)and(new.POWERFAULT=0)) then

begin

GETALARMRC=(select count(ID) from actalarms where objuin=new.objuin and ADDPARAM=1);

if (GETALARMRC>0) then

begin

delete from actalarms where OBJUIN=new.objuin and ADDPARAM=1;

insert into EvLog (EvTime1,ObjUIN,GrpN,ZoneN,EvUIN,Info1) values (current_timestamp,new.objuin,1, 0,1889,'Автоматическое завершение тревог о пропаже сети 220В');

end

end

end ^

CREATE TRIGGER OBJECTS_STATE_EV_UPDATED FOR OBJECTS_STATE 
ACTIVE AFTER UPDATE POSITION 0 
AS

DECLARE EVENT_NAME VARCHAR(100);

DECLARE REMOTE_OID INT;

DECLARE CHECKSTATE smallint;   /* 29.06.2012 */

begin

CHECKSTATE=0;

IF(NEW.GUARDSTATE1<>OLD.GUARDSTATE1) THEN

BEGIN

  CHECKSTATE=CHECKSTATE+1;

END

IF(NEW.ALARMSTATE1<>OLD.ALARMSTATE1) THEN

BEGIN

  CHECKSTATE=CHECKSTATE+1;

END

IF(NEW.TECHALARMSTATE1<>OLD.TECHALARMSTATE1) THEN

BEGIN

  CHECKSTATE=CHECKSTATE+1;

END

IF(NEW.RESERVLONG1<>OLD.RESERVLONG1) THEN

BEGIN

  CHECKSTATE=CHECKSTATE+1;

END

IF(NEW.GRPPERS<>OLD.GRPPERS) THEN

BEGIN

  CHECKSTATE=CHECKSTATE+1;

END

IF(NEW.OLDGRPPERS<>OLD.OLDGRPPERS) THEN

BEGIN

  CHECKSTATE=CHECKSTATE+1;

END

IF(NEW.POWERFAULT<>OLD.POWERFAULT) THEN

BEGIN

  CHECKSTATE=CHECKSTATE+1;

END

IF(NEW.CURRENT_CHAN<>OLD.CURRENT_CHAN) THEN

BEGIN

  CHECKSTATE=CHECKSTATE+1;

END

IF(NEW.AKBSTATE<>OLD.AKBSTATE) THEN

BEGIN

  CHECKSTATE=CHECKSTATE+1;

END

IF(NEW.TMPRALARM<>OLD.TMPRALARM) THEN

BEGIN

  CHECKSTATE=CHECKSTATE+1;

END

IF(CHECKSTATE>0)THEN

BEGIN

 EVENT_NAME ='OBJECTS_changed';

 POST_EVENT EVENT_NAME;

END

end ^

CREATE TRIGGER AI_OBJECTS_VINFO2 FOR OBJECTS_VINFO2 
ACTIVE BEFORE INSERT POSITION 0 
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID=GEN_ID(GEN_FOR_AI_OBJECTS_VINFO2,1); END ^

CREATE TRIGGER AI_OBJREGS FOR OBJREGS 
ACTIVE BEFORE INSERT POSITION 0 
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID=GEN_ID(GEN_FOR_AI_OBJREGS,1); END ^

CREATE TRIGGER AI_OBJTYPES FOR OBJTYPES 
ACTIVE BEFORE INSERT POSITION 0 
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID=GEN_ID(GEN_FOR_AI_OBJTYPES,1); END ^

CREATE TRIGGER AI_PCN_RINFO FOR PCN_RINFO 
ACTIVE BEFORE INSERT POSITION 0 
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID=GEN_ID(gen_PCN_RINFO,1); END ^

CREATE TRIGGER AI_PERSONAL FOR PERSONAL 
ACTIVE BEFORE INSERT POSITION 0 
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID=GEN_ID(GEN_FOR_AI_PERSONAL,1); END ^

CREATE TRIGGER AI_PERS_INSTALLER FOR PERS_INSTALLER 
ACTIVE BEFORE INSERT POSITION 0 
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID=GEN_ID(GEN_FOR_AI_PERS_INSTALLER,1); END ^

CREATE TRIGGER AI_PERS_MANAGER FOR PERS_MANAGER 
ACTIVE BEFORE INSERT POSITION 0 
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID=GEN_ID(GEN_FOR_AI_PERS_MANAGER,1); END ^

CREATE TRIGGER AI_PREG FOR PERS_REGISTERED 
ACTIVE BEFORE INSERT POSITION 0 
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID=GEN_ID(gen_preg,1); END ^

CREATE TRIGGER AI_PPK FOR PPK 
ACTIVE BEFORE INSERT POSITION 0 
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID=GEN_ID(GEN_FOR_AI_PPK,1); END ^

CREATE TRIGGER AI_PRSGROUP FOR PRSGROUP 
ACTIVE BEFORE INSERT POSITION 0 
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID=GEN_ID(GEN_FOR_AI_PRSGROUP,1); END ^

CREATE TRIGGER AI_PULT_INFO FOR PULT_INFO 
ACTIVE BEFORE INSERT POSITION 0 
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID=GEN_ID(GEN_FOR_AI_PULT_INFO,1); END ^

CREATE TRIGGER RADIO_PPK_BI FOR RADIO_PPK 
ACTIVE BEFORE INSERT POSITION 0 
AS BEGIN IF (NEW.R_N_ID IS NULL) THEN NEW.R_N_ID = GEN_ID(GEN_RADIO_PPK_ID,1); END ^

CREATE TRIGGER RADIO_PPK_AI0 FOR RADIO_PPK 
ACTIVE AFTER INSERT POSITION 0 
AS begin INSERT INTO ALLCHANGES (ID, SQL_TEXT, NAME_GEN) VALUES (GEN_ID(GEN_ALLCHANGES_ID, 1), 'INSERT INTO RADIO_PPK (R_N_ID,R_X,R_Y,R_NUM_OBJECT,R_WINDOW_VALIDATE,R_STATUS,R_COUNT_MINUTE,R_MAX_COUNT_MINUTE,R_ADRESS1,R_ADRESS2,R_ADRESS3,R_ADRESS4,R_LEVEL1,R_LEVEL2,R_LEVEL3,R_LEVEL4,R_CURRENT_ADRESS,R_CURRENT_LEVEL,R_COUNT_CONNECT_REAL,R_COUNT_CONNECT_OUTSIDE,R_HIDE_NUM_PPK,R_FLOAT_CODE_OUTSIDE) VALUES ('||COALESCE(NEW.R_N_ID, 'NULL')||','||COALESCE(NEW.R_X, 'NULL')||','||COALESCE(NEW.R_Y, 'NULL')||','||COALESCE(NEW.R_NUM_OBJECT, 'NULL')||','||COALESCE(NEW.R_WINDOW_VALIDATE, 'NULL')||','||COALESCE(NEW.R_STATUS, 'NULL')||','||COALESCE(NEW.R_COUNT_MINUTE, 'NULL')||','||COALESCE(NEW.R_MAX_COUNT_MINUTE, 'NULL')||','||COALESCE(NEW.R_ADRESS1, 'NULL')||','||COALESCE(NEW.R_ADRESS2, 'NULL')||','||COALESCE(NEW.R_ADRESS3, 'NULL')||','||COALESCE(NEW.R_ADRESS4, 'NULL')||','||COALESCE(NEW.R_LEVEL1, 'NULL')||','||COALESCE(NEW.R_LEVEL2, 'NULL')||','||COALESCE(NEW.R_LEVEL3, 'NULL')||','||COALESCE(NEW.R_LEVEL4, 'NULL')||','||COALESCE(NEW.R_CURRENT_ADRESS, 'NULL')||','||COALESCE(NEW.R_CURRENT_LEVEL, 'NULL')||','||COALESCE(NEW.R_COUNT_CONNECT_REAL, 'NULL')||','||COALESCE(NEW.R_COUNT_CONNECT_OUTSIDE, 'NULL')||','||COALESCE(NEW.R_HIDE_NUM_PPK, 'NULL')||','||COALESCE(NEW.R_FLOAT_CODE_OUTSIDE, 'NULL')||');','SET GENERATOR GEN_RADIO_PPK_ID TO '||COALESCE(NEW.R_N_ID, 'NULL'));execute procedure mess_change_radiopoint;end ^

CREATE TRIGGER RADIO_PPK_AU0 FOR RADIO_PPK 
ACTIVE AFTER UPDATE POSITION 0 
AS begin INSERT INTO ALLCHANGES (ID, SQL_TEXT) VALUES (GEN_ID(GEN_ALLCHANGES_ID, 1), 'UPDATE RADIO_PPK SET R_N_ID='||COALESCE(NEW.R_N_ID, 'NULL')||',R_X='||COALESCE(NEW.R_X, 'NULL')||',R_Y='||COALESCE(NEW.R_Y, 'NULL')||',R_NUM_OBJECT='||COALESCE(NEW.R_NUM_OBJECT, 'NULL')||',R_WINDOW_VALIDATE='||COALESCE(NEW.R_WINDOW_VALIDATE, 'NULL')||',R_STATUS='||COALESCE(NEW.R_STATUS, 'NULL')||',R_COUNT_MINUTE='||COALESCE(NEW.R_COUNT_MINUTE, 'NULL')||',R_MAX_COUNT_MINUTE='||COALESCE(NEW.R_MAX_COUNT_MINUTE, 'NULL')||',R_ADRESS1='||COALESCE(NEW.R_ADRESS1, 'NULL')||',R_ADRESS2='||COALESCE(NEW.R_ADRESS2, 'NULL')||',R_ADRESS3='||COALESCE(NEW.R_ADRESS3, 'NULL')||',R_ADRESS4='||COALESCE(NEW.R_ADRESS4, 'NULL')||',R_LEVEL1='||COALESCE(NEW.R_LEVEL1, 'NULL')||',R_LEVEL2='||COALESCE(NEW.R_LEVEL2, 'NULL')||',R_LEVEL3='||COALESCE(NEW.R_LEVEL3, 'NULL')||',R_LEVEL4='||COALESCE(NEW.R_LEVEL4, 'NULL')||',R_CURRENT_ADRESS='||COALESCE(NEW.R_CURRENT_ADRESS, 'NULL')||',R_CURRENT_LEVEL='||COALESCE(NEW.R_CURRENT_LEVEL, 'NULL')||',R_COUNT_CONNECT_REAL='||COALESCE(NEW.R_COUNT_CONNECT_REAL, 'NULL')||',R_COUNT_CONNECT_OUTSIDE='||COALESCE(NEW.R_COUNT_CONNECT_OUTSIDE, 'NULL')||',R_HIDE_NUM_PPK='||COALESCE(NEW.R_HIDE_NUM_PPK, 'NULL')||' WHERE (RADIO_PPK.R_N_ID='||NEW.R_N_ID||');' ); end ^

CREATE TRIGGER RADIO_PPK_BD0 FOR RADIO_PPK 
ACTIVE BEFORE DELETE POSITION 0 
AS begin INSERT INTO ALLCHANGES (ID, SQL_TEXT) VALUES (GEN_ID(GEN_ALLCHANGES_ID, 1), 'DELETE FROM RADIO_PPK WHERE R_N_ID='||OLD.R_N_ID); end ^

CREATE TRIGGER RADIO_PPK_AD0 FOR RADIO_PPK 
ACTIVE AFTER DELETE POSITION 0 
AS begin execute procedure mess_change_radiopoint; end ^

CREATE TRIGGER AI_SBS FOR SBS 
ACTIVE BEFORE INSERT POSITION 0 
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID=GEN_ID(GEN_FOR_AI_SBS,1); END ^

CREATE TRIGGER AI_SBS_ACTIV FOR SBS_ACTIV 
ACTIVE BEFORE INSERT POSITION 0 
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID=GEN_ID(GEN_FOR_AI_SBS_ACTIV,1); END ^

CREATE TRIGGER AI_SBS_PORT FOR SBS_PORT 
ACTIVE BEFORE INSERT POSITION 0 
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID=GEN_ID(GEN_FOR_AI_SBS_PORT,1); END ^

CREATE TRIGGER AI_SMS_MESS FOR SMS_MESS 
ACTIVE BEFORE INSERT POSITION 0 
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID=GEN_ID(GEN_FOR_AI_SMS_MESS,1); END ^

CREATE TRIGGER AI_SMS_TEXT FOR SMS_TEXT 
ACTIVE BEFORE INSERT POSITION 0 
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID=GEN_ID(GEN_FOR_AI_SMS_TEXT,1); END ^

CREATE TRIGGER AI_SV FOR SOFT_VER 
ACTIVE BEFORE INSERT POSITION 0 
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID=GEN_ID(gen_SV,1); END ^

CREATE TRIGGER TR_SRVLSTACT_UPDATE FOR SRVLSTACT 
ACTIVE AFTER UPDATE POSITION 0 
AS
DECLARE EVENT_NAME VARCHAR(100);
DECLARE REMOTE_OID INT;
begin
EVENT_NAME ='srvlstact_updated';
POST_EVENT EVENT_NAME;
end ^

CREATE TRIGGER AI_TAREP FOR TAREP 
ACTIVE BEFORE INSERT POSITION 0 
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID=GEN_ID(GEN_FOR_AI_TAREP,1); END ^

CREATE TRIGGER AI_UR_PARAMS FOR UR_PARAMS 
ACTIVE BEFORE INSERT POSITION 0 
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID=GEN_ID(GEN_FOR_AI_UR_PARAMS,1); END ^

CREATE TRIGGER AI_XOZORG FOR XOZORG 
ACTIVE BEFORE INSERT POSITION 0 
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID=GEN_ID(GEN_FOR_AI_XOZORG,1); END ^

CREATE TRIGGER AI_ZONES FOR ZONES 
ACTIVE BEFORE INSERT POSITION 0 
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID=GEN_ID(GEN_FOR_AI_ZONES,1); END ^


SET TERM ; ^
COMMIT WORK;

/* Grant permissions for this database */
GRANT EXECUTE ON FUNCTION USTRUPPERCASE TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_AI_MAINFO TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_ALLCHANGES_ID TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_DCT_CITY TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_DCT_CNTR TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_DCT_RG TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_FOR_AI_ACTALARMS TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_FOR_AI_ALARMREAS TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_FOR_AI_AREP TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_FOR_AI_CPTS_CHAN TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_FOR_AI_CPTS_INFO TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_FOR_AI_CPTS_OBJ_INFO TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_FOR_AI_CPTS_PERSONAL TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_FOR_AI_DELREAS TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_FOR_AI_DELREPORT TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_FOR_AI_ECS TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_FOR_AI_EVLOG TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_FOR_AI_FIXREAS TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_FOR_AI_FIXREPORT TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_FOR_AI_GLOBALCFG TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_FOR_AI_GPS_SRV TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_FOR_AI_GRP_ECS TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_FOR_AI_HARDLOG TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_FOR_AI_IMAGES TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_FOR_AI_JOURNAL TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_FOR_AI_MESSLIST TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_FOR_AI_OBJECTS TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_FOR_AI_OBJECTS_GPS TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_FOR_AI_OBJECTS_INFO TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_FOR_AI_OBJECTS_LA TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_FOR_AI_OBJECTS_STATE TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_FOR_AI_OBJECTS_VINFO2 TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_FOR_AI_OBJREGS TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_FOR_AI_OBJTYPES TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_FOR_AI_PERSONAL TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_FOR_AI_PPK TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_FOR_AI_PRSGROUP TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_FOR_AI_PULT_INFO TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_FOR_AI_SBS TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_FOR_AI_SBS_ACTIV TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_FOR_AI_SBS_PORT TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_FOR_AI_SMS_MESS TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_FOR_AI_SMS_TEXT TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_FOR_AI_TAREP TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_FOR_AI_UR_PARAMS TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_FOR_AI_XOZORG TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_FOR_AI_ZONES TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_FP_EVENTS_ID TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_FP_TYPE_EVENT_ID TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_GRPZN_ID TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_PCN_RINFO TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_PREG TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_RADIO_PPK_ID TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_SV TO PUBLIC;
