// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDBSettings() {
  return window['go']['main']['OperatorSettingsService']['GetDBSettings']();
}

export function SaveDBSettings(arg1) {
  return window['go']['main']['OperatorSettingsService']['SaveDBSettings'](arg1);
}
