package caslcompat

// buildFixtureEventTypes returns comprehensive event type lists for both Phoenix and MOST device types,
// used in the default fixture to populate MessageTranslators.
func buildFixtureEventTypes(phoenixType, mostType string) []UnifiedEventType {
	result := make([]UnifiedEventType, 0, 200)
	result = append(result, phoenixCIDEventTypes(phoenixType)...)
	result = append(result, mostBridgeEventTypes(mostType)...)
	return result
}

// evt is a compact constructor for UnifiedEventType entries.
func evt(dt string, code int, typeEvent string, additionalType int, name string, isAlarm int, uk, ru, en string) UnifiedEventType {
	return UnifiedEventType{
		DeviceType:     dt,
		Code:           code,
		TypeEvent:      typeEvent,
		AdditionalType: additionalType,
		EventByUser:    name,
		IsAlarm:        isAlarm,
		LangUK:         uk,
		LangRU:         ru,
		LangEN:         en,
	}
}

// cidEventTypes returns the full Contact ID / Satel protocol event table for the given device type.
// Covers all 386 standard CID codes used by Satel-compatible panels and Phoenix.
func cidEventTypes(dt string) []UnifiedEventType {
	return []UnifiedEventType{
		evt(dt, 100, "E", 1, "MEDICAL_ALARM", 1, "Медична тривога", "Медицинская тревога", "Medical alarm"),
		evt(dt, 101, "E", 0, "PERSONAL_DANGER", 1, "Персональна небезпека", "Персональная опасность", "Personal danger"),
		evt(dt, 102, "E", 0, "CANT_INALARM", 0, "Неможливість передачі під час тривоги", "Невозможность передачи при тревоге", "Can't send in alarm"),
		evt(dt, 110, "E", 1, "FIRE_ALARM", 1, "Пожежна тривога", "Пожарная тревога", "Fire alarm"),
		evt(dt, 110, "R", 1, "FIRE_RESTORE", 0, "Відновлення пожежі", "Восстановление пожара", "Fire restore"),
		evt(dt, 111, "E", 1, "SMOKE", 1, "Тривога диму", "Тревога дыма", "Smoke alarm"),
		evt(dt, 111, "R", 1, "SMOKE_RESTORE", 0, "Відновлення тривоги диму", "Восстановление тревоги дыма", "Smoke restore"),
		evt(dt, 112, "E", 1, "FIRE_START", 1, "Займання вогню", "Возгорание", "Ignition"),
		evt(dt, 112, "R", 1, "FIRE_START_RESTORE", 0, "Відновлення займання", "Восстановление возгорания", "Ignition restore"),
		evt(dt, 113, "E", 1, "WATER_LEAK", 1, "Протікання води", "Протечка воды", "Water leak"),
		evt(dt, 113, "R", 1, "WATER_LEAK_RESTORE", 0, "Відновлення протікання", "Восстановление протечки", "Water leak restore"),
		evt(dt, 114, "E", 1, "HEAT", 1, "Тривога по тепловому сенсору: перевищення температури", "Тревога по тепловому сенсору: превышение температуры", "Thermal sensor alarm: high temperature"),
		evt(dt, 114, "R", 1, "HEAT_RESTORE", 0, "Норма теплового сенсора", "Норма теплового сенсора", "Thermal sensor restore"),
		evt(dt, 115, "E", 1, "FIRE_KEYBOARD", 1, "Пожежа з клавіатури", "Пожар с клавиатуры", "Fire by keyboard"),
		evt(dt, 115, "R", 1, "FIRE_KEYBOARD_RESTORE", 0, "Відновлення пожежі з клавіатури", "Восстановление пожара с клавиатуры", "Fire by keyboard restore"),
		evt(dt, 116, "E", 1, "CID_116_E", 1, "CID 116", "CID 116", "CID 116"),
		evt(dt, 117, "E", 1, "FIRE", 1, "Вогонь", "Огонь", "Fire"),
		evt(dt, 117, "R", 1, "FIRE_ZONE_RESTORE", 0, "Відновлення вогню", "Восстановление огня", "Fire restore"),
		evt(dt, 118, "E", 1, "POSIBLE_FIRE", 1, "Ймовірна пожежна тривога", "Вероятная пожарная тревога", "Possible fire alarm"),
		evt(dt, 118, "R", 1, "POSIBLE_FIRE_RESTORE", 0, "Відновлення ймовірної пожежі", "Восстановление вероятной пожарной тревоги", "Possible fire restore"),
		evt(dt, 120, "E", 1, "ALM_BTN_PRS", 1, "Тривожна кнопка натиснута", "Тревожная кнопка нажата", "Panic alarm pressed"),
		evt(dt, 120, "R", 1, "ALM_BTN_RLZ", 0, "Тривожна кнопка відпущена", "Тревожная кнопка отпущена", "Panic alarm released"),
		evt(dt, 121, "E", 1, "FORCING", 1, "Примус", "Принуждение", "Compulsion to client"),
		evt(dt, 121, "R", 1, "FORCING_RESTORE", 0, "Відновлення примусу", "Восстановление принуждения", "Compulsion restore"),
		evt(dt, 122, "E", 1, "ALM_BTN_PRS", 1, "Тривожна кнопка натиснута", "Тревожная кнопка нажата", "Panic alarm pressed"),
		evt(dt, 122, "R", 1, "ALM_BTN_RLZ", 0, "Тривожна кнопка відпущена", "Тревожная кнопка отпущена", "Panic alarm released"),
		evt(dt, 123, "E", 1, "HEARING_ALARM", 1, "Чутна тривога", "Слышимая тревога", "Hearing alarm"),
		evt(dt, 123, "R", 1, "HEARING_ALARM_CANCEL", 0, "Відміна чутної тривоги", "Восстановление слышимой тревоги", "Hearing alarm cancelled"),
		evt(dt, 124, "E", 1, "DURESS_ACCESS_GRANTED", 1, "Примус – доступ надано", "Тревога принуждение, вход разрешен", "Duress – Access granted"),
		evt(dt, 124, "R", 1, "DURESS_ACCESS_GRANTED_CANCEL", 0, "Скасування тривоги примус, вхід дозволено", "Отмена тревоги принуждение, вход разрешен", "Duress – Access granted cancelled"),
		evt(dt, 125, "E", 1, "DURESS_EGRESS_GRANTED", 1, "Тривога примус, вихід дозволено", "Тревога принуждение, выход разрешен", "Duress – Egress granted"),
		evt(dt, 125, "R", 1, "DURESS_EGRESS_GRANTED_CANCEL", 0, "Відміна тривоги примус, вихід дозволено", "Отмена тревоги принуждение, выход разрешен", "Duress – Egress granted cancelled"),
		evt(dt, 126, "E", 1, "ALM_INNER_ZONE", 1, "Тривога в зоні внутрішня", "Тревога в зоне внутренняя", "Internal zone alarm"),
		evt(dt, 126, "R", 1, "ALM_INNER_ZONE_RESTORE", 0, "Норма відсутності охоронця", "Норма Отсутствие охранника", "Absence of guard normal"),
		evt(dt, 130, "E", 1, "ALM_BURGLARY", 1, "Охоронна тривога", "Охранная тревога", "Burglary alarm"),
		evt(dt, 130, "R", 1, "ALM_BURGLARY_RESTORE", 0, "Відновлення охоронної тривоги", "Восстановление охранной тревоги", "Burglary alarm restore"),
		evt(dt, 131, "E", 1, "ALM_PERIMETER", 1, "Тривога периметр", "Тревога периметр", "Perimeter alarm"),
		evt(dt, 131, "R", 1, "ALM_PERIMETER_RESTORE", 0, "Відновлення тривоги периметра", "Восстановление тревоги периметра", "Perimeter alarm restore"),
		evt(dt, 135, "E", 1, "INVASION_DAY_NIGHT", 1, "Вторгнення, зона день/ніч", "Вторжение, зона день/ночь", "Invasion, day/night zone"),
		evt(dt, 135, "R", 1, "INVASION_DAY_NIGHT_RESTORE", 0, "Відновлення вторгнення, зона день/ніч", "Восстановление вторжения, зона день/ночь", "Invasion day/night zone restore"),
		evt(dt, 136, "E", 1, "HEARING_ALARM", 1, "Чутна тривога", "Слышимая тревога", "Hearing alarm"),
		evt(dt, 136, "R", 1, "HEARING_ALARM_CANCEL", 0, "Відміна чутної тривоги", "Восстановление слышимой тревоги", "Hearing alarm cancelled"),
		evt(dt, 137, "E", 1, "ALARM_OPEN_TMP_DEVICE", 1, "Тривога тампер приладу", "Тревога тампер прибора", "Alarm device tamper"),
		evt(dt, 137, "R", 1, "NORM_TMP_DEVICE", 0, "Норма тампер приладу", "Норма тампер прибора", "Device tamper norm"),
		evt(dt, 138, "E", 1, "PROBABLE_BURGLARY", 1, "Ймовірна тривога злому", "Вероятная тревога взлома", "Probable burglary alarm"),
		evt(dt, 138, "R", 1, "PROBABLE_BURGLARY_RESTORE", 0, "Скасування ймовірної тривоги злому", "Отмена вероятной тревоги взлома", "Cancelling probable burglary alarm"),
		evt(dt, 139, "E", 1, "INTRUSION_VERIFIER_ALARM", 1, "Тривога, верифікатор проникнення", "Тревога, верификатор проникновения", "Alarm, intrusion verifier"),
		evt(dt, 139, "R", 1, "INTRUSION_VERIFIER_RESTORE", 0, "Відновлення, верифікатор проникнення", "Восстановление, верификатор проникновения", "Recovery, penetration verifier"),
		evt(dt, 141, "E", 1, "SENSOR_CABLE_BREAK", 1, "Шлейф датчиків обірваний", "Шлейф датчиков оборван", "Sensor cable interrupted"),
		evt(dt, 141, "R", 1, "SENSOR_CABLE_RESTORE", 0, "Відновлення обриву шлейфу датчиків", "Восстановление обрыва шлейфа датчиков", "Sensor loop restore"),
		evt(dt, 142, "E", 1, "SENSOR_LOOP_SHORT", 1, "Шлейф датчиків коротко замкнутий", "Шлейф датчиков коротко замкнут", "Sensor loop short-circuit"),
		evt(dt, 142, "R", 1, "SENSOR_LOOP_SHORT_RESTORE", 0, "Відновлення короткого замикання шлейфу", "Восстановление короткого замыкания шлейфа", "Sensor loop short-circuit restore"),
		evt(dt, 143, "E", 1, "EXPANSION_MODULE_FAULT", 1, "Несправність модуля розширення", "Неисправность модуля расширения", "Expansion module defective"),
		evt(dt, 143, "R", 1, "EXPANSION_MODULE_RESTORE", 0, "Відновлення модуля розширення", "Восстановление модуля расширения", "Expansion module restore"),
		evt(dt, 146, "E", 1, "SILENT_INTRUSION", 1, "Тиха тривога вторгнення", "Тихая тревога вторжения", "Silent intrusion alarm"),
		evt(dt, 146, "R", 1, "SILENT_INTRUSION_RESTORE", 0, "Відновлення тихої тривоги вторгнення", "Восстановление тихой тревоги вторжения", "Silent intrusion restore"),
		evt(dt, 147, "E", 1, "NO_COMM_DETECTOR", 1, "Немає зв'язку з сповіщувачем", "Нет связи с извещателем", "No communication with detector"),
		evt(dt, 147, "R", 1, "COMM_DETECTOR_RESTORE", 0, "Відновлення зв'язку з сповіщувачем", "Восстановление связи с извещателем", "Communication with detector restored"),
		evt(dt, 150, "E", 1, "ALM_24H_NON_SECURITY", 1, "Тривога 24 годинна неохоронна зона", "Тревога 24 часовая не охранная зона", "Alarm 24 hour non-security zone"),
		evt(dt, 150, "R", 1, "ALM_24H_NON_SECURITY_RESTORE", 0, "Відновлення тривоги 24 годинної зони", "Восстановление тревоги 24 часовой зоны", "24 hour zone alarm restore"),
		evt(dt, 151, "E", 1, "GAS_ALARM", 1, "Газова тривога", "Газовая тревога", "Gas alarm"),
		evt(dt, 151, "R", 1, "GAS_RESTORE", 0, "Відновлення газової тривоги", "Восстановление газовой тревоги", "Gas alarm restore"),
		evt(dt, 152, "E", 1, "COOLING", 1, "Охолодження", "Охлаждение", "Cooling"),
		evt(dt, 152, "R", 1, "COOLING_RESTORE", 0, "Норма охолодження", "Норма охлаждения", "Cooling rate"),
		evt(dt, 153, "E", 1, "HEAT_LOSS", 1, "Втрата тепла", "Потеря тепла", "Loss of heat"),
		evt(dt, 153, "R", 1, "HEAT_LOSS_RESTORE", 0, "Норма тепла", "Норма тепла", "Heat rate"),
		evt(dt, 155, "E", 1, "FOIL_BREAK", 1, "Обрив фольги", "Обрыв фольги", "Foil break"),
		evt(dt, 155, "R", 1, "FOIL_RESTORE", 0, "Норма фольги", "Норма фольги", "Foil rate"),
		evt(dt, 156, "E", 1, "DAY_ZONE_FAULT", 1, "Несправність денної зони", "Неисправность дневной зоны", "Day zone malfunction"),
		evt(dt, 156, "R", 1, "DAY_ZONE_RESTORE", 0, "Норма денної зони", "Норма дневной зоны", "Day zone rate"),
		evt(dt, 158, "E", 1, "HIGH_TEMP", 1, "Висока температура", "Высокая температура", "High temperature"),
		evt(dt, 158, "R", 1, "HIGH_TEMP_RESTORE", 0, "Відновлення тривоги високої температури", "Восстановление тревоги высокой температуры", "High temperature alarm recovery"),
		evt(dt, 159, "E", 1, "LOW_TEMP", 1, "Низька температура", "Низкая температура", "Low temperature"),
		evt(dt, 159, "R", 1, "LOW_TEMP_RESTORE", 0, "Відновлення тривоги низької температури", "Восстановление тревоги низкой температуры", "Low temperature alarm recovery"),
		evt(dt, 161, "E", 1, "AIRFLOW_LOSS", 1, "Втрата повітряного потоку", "Потеря воздушного потока", "Loss of airflow"),
		evt(dt, 161, "R", 1, "AIRFLOW_RESTORE", 0, "Норма повітряного потоку", "Норма воздушного потока", "Air flow rate"),
		evt(dt, 163, "E", 1, "TANK_LEVEL_ALARM", 1, "Невірний рівень у резервуарі", "Неверный уровень в резервуаре", "Incorrect tank level"),
		evt(dt, 163, "R", 1, "TANK_LEVEL_RESTORE", 0, "Норма рівня у резервуарі", "Норма уровня в резервуаре", "Tank level rate"),
		evt(dt, 200, "E", 1, "FIRE_RELIEF", 0, "Скидання пожежі", "Сброс пожара", "Fire relief"),
		evt(dt, 201, "E", 1, "LOW_WATER_PRESSURE", 1, "Низький тиск води", "Низкое давление воды", "Low water pressure"),
		evt(dt, 201, "R", 1, "WATER_PRESSURE_RESTORE", 0, "Норма тиску води", "Норма давления воды", "Water pressure rate"),
		evt(dt, 202, "E", 0, "LOW_CO2", 1, "Низька концентрація СО2", "Низкая концентрация СО2", "Low CO2 concentration"),
		evt(dt, 202, "R", 0, "CO2_RESTORE", 0, "Норма концентрації СО2", "Норма концентрации СО2", "CO2 concentration rate"),
		evt(dt, 204, "E", 1, "LOW_WATER_LEVEL", 0, "Низький рівень води", "Низкий уровень воды", "Low water level"),
		evt(dt, 204, "R", 1, "WATER_LEVEL_RESTORE", 0, "Норма рівня води", "Норма уровня воды", "Water level rate"),
		evt(dt, 207, "E", 0, "ARM_RESTRICTION", 0, "Виконано заборону постановки на охорону", "Выполнен запрет постановки в охрану", "Restriction of arming performed"),
		evt(dt, 208, "E", 0, "SIM_CHANGE", 0, "Зміна активної SIM-картки", "Смена активной SIM-карты", "Change active SIM card"),
		evt(dt, 209, "E", 0, "GSM_RESET", 0, "Скидання живлення GSM-модуля", "Сброс питания GSM-модуля", "Resetting the GSM module power supply"),
		evt(dt, 303, "E", 0, "RAM_CHECKSUM_ERROR", 0, "Помилка контрольної суми ОЗУ", "Ошибка контрольной суммы ОЗУ", "RAM checksum error"),
		evt(dt, 303, "R", 0, "RAM_CHECKSUM_RESTORE", 0, "Норма контрольної суми ОЗУ", "Норма контрольной суммы ОЗУ", "RAM checksum rate"),
		evt(dt, 304, "E", 0, "ROM_CHECKSUM_ERROR", 0, "Помилка контрольної суми ПЗУ", "Ошибка контрольной суммы ПЗУ", "ROM checksum error"),
		evt(dt, 304, "R", 0, "ROM_CHECKSUM_RESTORE", 0, "Норма контрольної суми ПЗУ", "Норма контрольной суммы ПЗУ", "ROM checksum rate"),
		evt(dt, 308, "R", 0, "PPK_CONN_OK", 0, "ППК підключений", "ППК подключен", "PPK connected"),
		evt(dt, 309, "E", 0, "BATTERY_TEST_FAIL", 0, "Невдача тесту акумулятора", "Неудача теста аккумулятора", "Failed battery test"),
		evt(dt, 309, "R", 0, "BATTERY_TEST_OK", 0, "Норма тесту акумулятора", "Норма теста аккумулятора", "Battery test rate"),
		evt(dt, 310, "E", 0, "GROUND_FAULT", 0, "Несправність заземлення", "Неисправность заземления", "Ground fault"),
		evt(dt, 310, "R", 0, "GROUND_RESTORE", 0, "Норма заземлення", "Норма заземления", "Grounding rate"),
		evt(dt, 312, "E", 0, "POWER_OVERLOAD", 0, "Перевантаження джерела живлення", "Перегрузка источника питания", "Power supply overload"),
		evt(dt, 312, "R", 0, "POWER_OVERLOAD_RESTORE", 0, "Норма джерела живлення", "Норма источника питания", "Power supply rate"),
		evt(dt, 313, "E", 0, "SOFTWARE_RESET", 0, "Програмне скидання інженером", "Программный сброс инженером", "Software reset by engineer"),
		evt(dt, 315, "E", 0, "BACKUP_CHANNEL_FAIL", 0, "Аварія резервного каналу (відсутність SIM карти 2)", "Авария резервного канала (отсутствие SIM карты 2)", "Backup channel failure (no SIM2)"),
		evt(dt, 316, "E", 0, "SIM1_ACTIVE", 0, "Використовується основний канал передачі (SIM1)", "Используется основной канал передачи (SIM1)", "Main transmission channel (SIM1) is used"),
		evt(dt, 317, "E", 0, "SIM2_ACTIVE", 0, "Використовується резервний канал передачі (SIM2)", "Используется резервный канал передачи (SIM2)", "Backup transmission channel (SIM2) is used"),
		evt(dt, 317, "R", 0, "SIM2_ACTIVE_RESTORE", 0, "Використовується резервний канал передачі (SIM2)", "Используется резервный канал передачи (SIM2)", "Backup transmission channel (SIM2) restore"),
		evt(dt, 319, "E", 0, "COMM_PANEL_LOSS", 1, "Втрата зв'язку комунікатора з ППК", "Потеря связи коммуникатора с ППК", "Loss of communication between communicator and panel"),
		evt(dt, 319, "R", 0, "COMM_PANEL_RESTORE", 0, "Відновлення зв'язку комунікатора з ППК", "Восстановление связи коммуникатора с ППК", "Restore communication between communicator and panel"),
		evt(dt, 320, "E", 1, "SIREN_RELAY_FAULT", 0, "Несправність сирени/реле", "Неисправность сирены/реле", "Siren/relay malfunction"),
		evt(dt, 320, "R", 1, "SIREN_RELAY_RESTORE", 0, "Норма сирени/реле", "Норма сирены/реле", "Siren/relay rate"),
		evt(dt, 321, "E", 1, "SIREN1_FAULT", 0, "Несправність сирени 1", "Неисправность сирены 1", "Siren 1 malfunction"),
		evt(dt, 321, "R", 1, "SIREN1_RESTORE", 0, "Норма сирени 1", "Норма сирены 1", "Siren 1 rate"),
		evt(dt, 322, "E", 0, "SIREN2_FAULT", 0, "Несправність сирени 2", "Неисправность сирены 2", "Siren 2 malfunction"),
		evt(dt, 322, "R", 0, "SIREN2_RESTORE", 0, "Норма сирени 2", "Норма сирены 2", "Siren 2 rate"),
		evt(dt, 324, "E", 1, "RELAY_FAULT", 0, "Несправність реле", "Неисправность реле", "Relay malfunction"),
		evt(dt, 324, "R", 0, "RELAY_RESTORE", 0, "Норма реле", "Норма реле", "Relay rate"),
		evt(dt, 330, "E", 1, "KEYBOARD_FAULT", 0, "Несправність клавіатури", "Неисправность клавиатуры", "Faulty keyboard"),
		evt(dt, 330, "R", 0, "KEYBOARD_RESTORE", 0, "Норма системної периферії", "Норма системной периферии", "System periphery rate"),
		evt(dt, 331, "E", 0, "SENSOR_LOOP_BREAK", 1, "Шлейф датчиків обірваний", "Шлейф датчиков оборван", "Sensor cable interrupted"),
		evt(dt, 331, "R", 0, "SENSOR_LOOP_BREAK_RESTORE", 0, "Норма шлейфу датчиків", "Норма шлейфа датчиков", "Sensor loop rate"),
		evt(dt, 332, "E", 0, "KZ_LINE", 1, "КЗ лінії", "КЗ линии", "Short circuit line"),
		evt(dt, 332, "R", 0, "KZ_LINE_RESTORE", 0, "Відновлення КЗ лінії", "Восстановление КЗ линии", "Short circuit line restore"),
		evt(dt, 334, "E", 0, "REPEATER_FAULT", 1, "Несправність повторювача", "Неисправность повторителя", "Repeater malfunction"),
		evt(dt, 334, "R", 0, "REPEATER_RESTORE", 0, "Норма повторювача", "Норма повторителя", "Repeater rate"),
		evt(dt, 339, "E", 1, "MODULE_RELOAD", 0, "Перезавантаження модуля", "Перезагрузка модуля", "Reload the module"),
		evt(dt, 342, "E", 0, "MODULE_NO_AC", 1, "Відсутність живлення модуля (змінний струм)", "Отсутствие питания модуля (переменный ток)", "No AC power to module"),
		evt(dt, 342, "R", 0, "MODULE_AC_RESTORE", 0, "Відновлення живлення модуля (змінний струм)", "Восстановление питания модуля (переменный ток)", "Module AC power restore"),
		evt(dt, 345, "E", 0, "SIM_CHANGE_ACTIVE", 0, "Зміна активної SIM-картки", "Смена активной SIM-карты", "Change active SIM card"),
		evt(dt, 350, "E", 0, "NO_COMM_MONITORING", 1, "Немає зв'язку зі станцією моніторингу", "Нет связи со станцией мониторинга", "No connection with monitoring station"),
		evt(dt, 350, "R", 0, "COMM_MONITORING_RESTORE", 0, "Відновлення зв'язку зі станцією моніторингу", "Восстановление связи со станцией мониторинга", "Monitoring station connection restored"),
		evt(dt, 351, "E", 0, "PHONE_LINE1_FAULT", 0, "Несправність телефонної лінії 1", "Неисправность телефонной линии 1", "Telephone line 1 trouble"),
		evt(dt, 351, "R", 1, "PHONE_LINE1_RESTORE", 0, "Відновлення телефонної лінії 1", "Восстановление телефонной линии 1", "Telephone line 1 restore"),
		evt(dt, 352, "E", 0, "PHONE_LINE2_FAULT", 0, "Несправність телефонної лінії 2", "Неисправность телефонной линии 2", "Telephone line 2 trouble"),
		evt(dt, 352, "R", 0, "PHONE_LINE2_RESTORE", 0, "Відновлення телефонної лінії 2", "Восстановление телефонной линии 2", "Telephone line 2 restore"),
		evt(dt, 353, "E", 0, "LONG_RANGE_TX_FAULT", 0, "Несправність передавача дальньої дії", "Неисправность передатчика дальнего действия", "Long range transmitter malfunction"),
		evt(dt, 353, "R", 0, "LONG_RANGE_TX_RESTORE", 0, "Норма передавача дальньої дії", "Норма передатчика дальнего действия", "Long range transmitter rate"),
		evt(dt, 354, "E", 0, "EVENT_TRANSMISSION_ERROR", 0, "Помилка передачі події", "Ошибка передачи события", "Event transmission error"),
		evt(dt, 354, "R", 0, "COMMUNICATE_EVENT_FAIL", 0, "Помилка передачі події (відновлення)", "Ошибка передачи события (восстановление)", "Failure to communicate event restore"),
		evt(dt, 355, "E", 0, "RADIO_CTRL_LOSS", 0, "Втрата контролю радіокерування", "Потеря контроля радиоуправления", "Loss of radio control"),
		evt(dt, 355, "R", 0, "RADIO_CTRL_RESTORE", 0, "Норма контролю радіокерування", "Норма контроля радиоуправления", "Radio control rate"),
		evt(dt, 356, "E", 1, "MASTER_COMM_LOSS", 0, "Втрата зв'язку з провідним пристроєм", "Потеря связи с ведущим устройством", "Lost communication with master"),
		evt(dt, 357, "E", 1, "GSM_MODULE_RESTART", 0, "Перезавантаження GSM модуля", "Перезагрузка GSM модуля", "GSM module restart"),
		evt(dt, 358, "E", 0, "ADDR_LOOP_SHORT", 1, "КЗ адресного шлейфу", "КЗ адресного шлейфа", "Short circuit addressable loop"),
		evt(dt, 359, "E", 0, "DEVICE_OFFLINE", 1, "Немає зв'язку з ППК", "Нет связи с ППК", "No connection with panel"),
		evt(dt, 359, "R", 0, "DEVICE_ONLINE", 0, "Зв'язок з ППК відновлено", "Связь с ППК восстановлена", "Panel connection restored"),
		evt(dt, 370, "E", 0, "PROTECTION_LOOP_FAULT", 1, "Захисний шлейф несправний", "Защитный шлейф неисправен", "Protection loop faulty"),
		evt(dt, 370, "R", 0, "PROTECTION_LOOP_RESTORE", 0, "Захисний шлейф справний", "Защитный шлейф исправен", "Protection loop working"),
		evt(dt, 371, "E", 0, "PROTECTION_LOOP_BREAK", 1, "Захисний шлейф обірваний", "Защитный шлейф оборван", "Protection loop interrupted"),
		evt(dt, 371, "R", 0, "PROTECTION_LOOP_BREAK_RESTORE", 0, "Норма захисного шлейфу", "Норма защитного шлейфа", "Protection loop rate"),
		evt(dt, 374, "E", 0, "EXIT_ERROR", 1, "Помилка при виході", "Ошибка при выходе", "Error on exit"),
		evt(dt, 374, "R", 0, "EXIT_ERROR_CANCEL", 0, "Скасування помилки при виході", "Отмена ошибки при выходе", "Cancel error on exit"),
		evt(dt, 375, "E", 0, "PANIC_ZONE_FAULT", 1, "Несправність зони Паніка", "Неисправность зоны Паника", "Panic zone trouble"),
		evt(dt, 375, "R", 0, "PANIC_ZONE_RESTORE", 0, "Норма зони Паніка", "Норма зоны Паника", "Panic zone rate"),
		evt(dt, 376, "E", 0, "INVASION_ZONE_FAULT", 1, "Несправність зони вторгнення", "Неисправность зоны вторжения", "Invasion zone malfunction"),
		evt(dt, 376, "R", 0, "INVASION_ZONE_RESTORE", 0, "Норма зони вторгнення", "Норма зоны вторжения", "Invasion zone rate"),
		evt(dt, 378, "E", 0, "LINKED_ZONES_FAULT", 1, "Несправність пов'язаних зон", "Неисправность связанных зон", "Fault in linked zones"),
		evt(dt, 378, "R", 0, "LINKED_ZONES_RESTORE", 0, "Норма пов'язаних зон", "Норма связанных зон", "Rate of linked zones"),
		evt(dt, 380, "E", 0, "ZONE_FAULT", 1, "Несправність зони", "Неисправность зоны", "Zone fault"),
		evt(dt, 380, "R", 0, "ZONE_FAULT_RESTORE", 0, "Норма зони", "Норма зоны", "Zone rate"),
		evt(dt, 382, "E", 0, "RPM_COMM_LOSS", 0, "Втрата зв'язку RPM", "Потеря связи RPM", "Loss of communication RPM"),
		evt(dt, 382, "R", 0, "RPM_COMM_RESTORE", 0, "Норма зв'язку RPM", "Норма связи RPM", "Communication rate RPM"),
		evt(dt, 383, "E", 0, "ALARM_TMP_DETECTOR", 1, "Тривога тампер датчика", "Тревога тампер датчика", "Alarm tamper detector"),
		evt(dt, 383, "R", 0, "NORM_TMP_DETECTOR", 0, "Норма тампер датчику", "Норма тампер датчика", "Detector tamper norm"),
		evt(dt, 385, "E", 0, "SMOKE_DETECTOR_HIGH_SENS", 1, "Висока чутливість детектора диму", "Высокая чувствительность детектора дыма", "High sensitivity of smoke detector"),
		evt(dt, 385, "R", 0, "SMOKE_DETECTOR_HIGH_SENS_RESTORE", 0, "Норма чутливості детектора диму", "Норма чувствительности детектора дыма", "Smoke detector sensitivity rate"),
		evt(dt, 386, "E", 0, "SMOKE_DETECTOR_LOW_SENS", 1, "Низька чутливість детектора диму", "Низкая чувствительность детектора дыма", "Low sensitivity of smoke detector"),
		evt(dt, 386, "R", 0, "SMOKE_DETECTOR_SENS_RESTORE", 0, "Норма чутливості детектора диму", "Норма чувствительности детектора дыма", "Smoke detector sensitivity restore"),
		evt(dt, 392, "E", 0, "FREQ_DRIFT_FAULT", 0, "Компенсація дрейфу частоти", "Компенсация дрейфа частоты", "Frequency drift compensation"),
		evt(dt, 400, "E", 2, "GROUP_OFF", 0, "Зняття групи", "Снятие группы", "Group disarmed"),
		evt(dt, 400, "R", 2, "GROUP_ON", 0, "Постановка групи", "Взятие группы", "Group armed"),
		evt(dt, 401, "E", 2, "GROUP_OFF", 0, "Зняття з охорони", "Снятие с охраны", "Disarmed"),
		evt(dt, 401, "R", 2, "GROUP_ON", 0, "Постановка під охорону", "Постановка под охрану", "Armed"),
		evt(dt, 402, "E", 2, "GROUP_OFF", 0, "Зняття з охорони", "Снятие с охраны", "Disarmed"),
		evt(dt, 402, "R", 2, "GROUP_ON", 0, "Постановка під охорону", "Постановка под охрану", "Armed"),
		evt(dt, 403, "E", 2, "AUTO_OFF", 0, "Автоматичне зняття групи", "Автоматическое снятие группы", "Automatic group disarm"),
		evt(dt, 403, "R", 2, "AUTO_ON", 0, "Автоматичне взяття групи", "Автоматическое взятие группы", "Automatic group arm"),
		evt(dt, 404, "E", 2, "OFF_DELAY", 0, "Зняття групи із затримкою", "Снятие группы с опозданием", "Group disarm with delay"),
		evt(dt, 405, "E", 2, "OFF_LATER", 0, "Відстрочка зняття групи", "Отсрочка снятия группы", "Group disarm will later"),
		evt(dt, 405, "R", 2, "ON_LATER", 0, "Відстрочка взяття групи", "Отсрочка взятие группы", "Group arm will later"),
		evt(dt, 406, "E", 2, "OFF_CANCEL", 0, "Відміна взяття групи", "Отмена взятие группы", "Group arm cancelled"),
		evt(dt, 407, "E", 2, "OFF_DISTANT", 0, "Дистанційне зняття групи", "Дистанционное снятие группы", "Group disarm from distance"),
		evt(dt, 407, "R", 2, "ON_DISTANT", 0, "Дистанційне взяття групи", "Дистанционное взятие группы", "Group arm from distance"),
		evt(dt, 408, "R", 2, "ON_QUICK", 0, "Швидке взяття групи", "Быстрое взятие группы", "Quick group arm"),
		evt(dt, 421, "E", 0, "ACCESS_DENIED", 0, "Відмова доступу", "Отказ доступа", "Access denied"),
		evt(dt, 421, "R", 0, "ACCESS_DENIED_CANCEL", 0, "Скасування відмови доступу", "Отмена отказа доступа", "Cancel access denied"),
		evt(dt, 422, "E", 0, "USER_ACCESS", 0, "Повідомлення про доступ користувача", "Сообщение о доступе пользователя", "User access message"),
		evt(dt, 424, "E", 0, "EXIT_DENIED", 0, "Вихід Заборонено", "Выход Запрещен", "Exit denied"),
		evt(dt, 425, "E", 0, "EXIT_ALLOWED", 0, "Вихід дозволено", "Выход разрешен", "Exit allowed"),
		evt(dt, 426, "E", 0, "DOOR_LEFT_OPEN", 0, "Двері залишені у відкритому стані", "Дверь оставлена в открытом состоянии", "Door left open"),
		evt(dt, 426, "R", 0, "DOOR_LEFT_OPEN_CANCEL", 0, "Скасування: Двері залишені у відкритому стані", "Отмена: Дверь оставлена в открытом состоянии", "Cancel door left open"),
		evt(dt, 427, "E", 0, "DOOR_STATE_FAULT", 1, "Несправність контролю стану дверей", "Неисправность контроля состояния двери", "Door state control malfunction"),
		evt(dt, 427, "R", 0, "DOOR_STATE_RESTORE", 0, "Норма контролю стану дверей", "Норма контроля состояния двери", "Door state control rate"),
		evt(dt, 431, "E", 0, "ACCESS_THREAT_CHANGE", 0, "Зміна рівня загрози доступу", "Изменение уровня угрозы доступа", "Changing threat level of access"),
		evt(dt, 431, "R", 2, "KEYFOB_ARM", 0, "Постановка під охорону брелоком", "Постановка под охрану брелком", "Arming with key fob"),
		evt(dt, 450, "E", 2, "ARM_RESTRICTION", 0, "Виконано заборону постановки під охорону", "Выполнен запрет постановки под охрану", "Restriction of arming performed"),
		evt(dt, 450, "R", 2, "ARM_RESTRICTION_CANCEL", 0, "Скасування заборони постановки під охорону", "Отмена запрета постановки под охрану", "Cancelling prohibition of arming"),
		evt(dt, 455, "E", 2, "AUTO_ARM_FAIL", 0, "Невдача автоматичної постановки під охорону", "Неудача автоматической постановки под охрану", "Failure of automatic arming"),
		evt(dt, 463, "E", 0, "REARM_AFTER_ALARM", 0, "Перестановка після тривоги", "Перепостановка после тревоги", "Re-arming after alarm"),
		evt(dt, 464, "E", 2, "AUTO_ARM_EXTENDED", 0, "Автоматична постановка продовжена", "Автоматическая постановка продлена", "Automatic arming extended"),
		evt(dt, 464, "R", 2, "AUTO_ARM_EXTENDED_OFF", 0, "Автоматична постановка продовжена (вимк.)", "Автоматическая постановка продлена (выкл.)", "Automatic arming extended off"),
		evt(dt, 465, "E", 1, "PANIC_ALARM_CLEAR", 1, "Скидання тривоги Паніка", "Сброс тревоги Паника", "Alarm clearing panic"),
		evt(dt, 466, "E", 2, "SERVICE_ARM", 0, "Увімкнення охорони сервісною службою", "Включение охраны сервисной службой", "Arming by service"),
		evt(dt, 466, "R", 2, "SERVICE_DISARM", 0, "Вимкнення охорони сервісною службою", "Выключение охраны сервисной службой", "Disarming by service"),
		evt(dt, 501, "E", 1, "READER_LOCKED", 1, "Зчитувач контролю доступу заблоковано", "Считыватель контроля доступа заблокирован", "Access control reader locked"),
		evt(dt, 501, "R", 1, "READER_UNLOCKED", 0, "Зчитувач контролю доступу розблоковано", "Считыватель контроля доступа разблокирован", "Access control reader unlocked"),
		evt(dt, 520, "E", 1, "RELAY_OFF", 1, "Реле вимкнено", "Реле выключено", "Relay off"),
		evt(dt, 520, "R", 1, "RELAY_ON", 0, "Реле увімкнено", "Реле включено", "Relay on"),
		evt(dt, 551, "E", 0, "PHONE_COMM_OFF", 0, "Телефонний комунікатор вимкнено", "Телефонный коммуникатор отключен", "Telephone communicator disabled"),
		evt(dt, 551, "R", 0, "PHONE_COMM_ON", 0, "Телефонний комунікатор увімкнено", "Телефонный коммуникатор включен", "Telephone communicator enabled"),
		evt(dt, 552, "E", 0, "RADIO_TX_ON", 0, "Радіопередавач увімкнено", "Радиопередатчик включен", "Radio transmitter enabled"),
		evt(dt, 552, "R", 0, "RADIO_TX_OFF", 0, "Радіопередавач вимкнено", "Радиопередатчик отключен", "Radio transmitter disabled"),
		evt(dt, 553, "E", 1, "REMOTE_UPLOAD_OFF", 0, "Віддалене завантаження/вивантаження вимкнено", "Удалённая загрузка/выгрузка отключена", "Remote upload/download disabled"),
		evt(dt, 553, "R", 1, "REMOTE_UPLOAD_ON", 0, "Видалене завантаження/вивантаження увімкнено", "Удалённая загрузка/выгрузка включена", "Remote upload/download enabled"),
		evt(dt, 570, "E", 1, "LOOP_BYPASS_SET", 0, "Встановлення обходу шлейфу", "Установка обхода шлейфа", "Loop bypass set"),
		evt(dt, 570, "R", 1, "LOOP_BYPASS_CANCEL", 0, "Скасування обходу шлейфу", "Отмена обхода шлейфа", "Loop bypass cancel"),
		evt(dt, 571, "E", 1, "FIRE_ZONE_BYPASS", 0, "Обхід пожежної зони", "Обход пожарной зоны", "Fire zone bypass"),
		evt(dt, 571, "R", 1, "FIRE_ZONE_BYPASS_CANCEL", 0, "Скасування обходу пожежної зони", "Отмена обхода пожарной зоны", "Fire zone bypass cancel"),
		evt(dt, 572, "E", 1, "BYPASS_24H", 0, "Обхід 24-годинної зони", "Обход 24-часовой зоны", "Bypass 24h zone"),
		evt(dt, 572, "R", 1, "BYPASS_24H_CANCEL", 0, "Скасування обходу 24-годинної зони", "Отмена обхода 24-часовой зоны", "Bypass 24h zone cancel"),
		evt(dt, 573, "E", 0, "BYPASS_INVASION_ZONE", 0, "Обхід зони вторгнення", "Обход зоны вторжения", "Bypass invasion zone"),
		evt(dt, 573, "R", 0, "RESTORE_BYPASS_INVASION_ZONE", 0, "Відміна обходу зони вторгнення", "Отмена обхода зоны вторжения", "Cancel bypass invasion zone"),
		evt(dt, 580, "E", 1, "PPK_AC_CTRL_OFF", 0, "Вимкнення контролю основного живлення ППК (220В)", "Выключение контроля основного питания ППК (220В)", "Disabling AC control of panel (220V)"),
		evt(dt, 580, "R", 1, "PPK_AC_CTRL_ON", 0, "Увімкнення контролю основного живлення ППК (220В)", "Включение контроля основного питания ППК (220В)", "Enabling AC control of panel (220V)"),
		evt(dt, 581, "E", 1, "SIREN_CTRL_OFF", 0, "Вимкнення контролю сирени", "Выключение контроля сирены", "Siren control off"),
		evt(dt, 581, "R", 1, "SIREN_CTRL_ON", 0, "Увімкнення контролю сирени", "Включение контроля сирены", "Siren control on"),
		evt(dt, 582, "E", 1, "BATTERY_CTRL_OFF", 0, "Вимкнення контролю АКБ", "Выключение контроля АКБ", "Battery monitoring disabled"),
		evt(dt, 582, "R", 1, "BATTERY_CTRL_ON", 0, "Увімкнення контролю АКБ", "Включение контроля АКБ", "Battery monitoring enabled"),
		evt(dt, 600, "E", 0, "PERIODIC_TEST", 0, "Періодичний тест", "Периодический тест", "Periodic test"),
		evt(dt, 601, "E", 0, "MANUAL_TEST", 1, "Ручний тест", "Ручной тест", "Manual test"),
		evt(dt, 602, "E", 0, "PERIODIC_TEST", 0, "Тест", "Тест", "Test"),
		evt(dt, 602, "R", 0, "PERIODIC_TEST_RESTORE", 1, "Тест (відновлення)", "Тест (восстановление)", "Test restore"),
		evt(dt, 603, "E", 0, "PING", 0, "PING", "PING", "PING"),
		evt(dt, 604, "E", 0, "FIRE_TEST", 0, "Пожежний тест", "Пожарный тест", "Fire test"),
		evt(dt, 605, "E", 0, "STATUS_REPORT", 0, "Звіт стану", "Отчет состояния", "Status report"),
		evt(dt, 606, "E", 0, "VOICE_CONN", 0, "Голосовий зв'язок", "Голосовая связь", "Voice connection"),
		evt(dt, 607, "E", 0, "TEST_BYPASS", 0, "Тестовий режим обходу", "Тестовый режим обхода", "Test bypass mode"),
		evt(dt, 608, "E", 0, "PERIODIC_TEST_FAULT", 0, "Періодичний тест - Системна несправність присутня", "Периодический тест - Системная неисправность присутствует", "Periodic test - System fault present"),
		evt(dt, 608, "R", 0, "PERIODIC_TEST_OK", 0, "Періодичний тест - Системна несправність відсутня", "Периодический тест - Системная неисправность отсутствует", "Periodic test - No system fault"),
		evt(dt, 610, "E", 0, "DEVICE_COMM_REPORT", 0, "Звіт: зв'язок із приладом є", "Отчет: связь с прибором есть", "Report: device communication OK"),
		evt(dt, 611, "E", 1, "CHECKPOINT_VIOLATION", 0, "Порушення контрольної точки", "Нарушение контрольной точки", "Checkpoint violation"),
		evt(dt, 611, "R", 1, "CHECKPOINT_RESTORE", 0, "Норма контрольної точки", "Норма контрольной точки", "Checkpoint rate"),
		evt(dt, 616, "E", 0, "SERVICE_CALL", 1, "Виклик сервісної служби", "Вызов сервисной службы", "Service call"),
		evt(dt, 616, "R", 0, "SERVICE_CALL_CANCEL", 0, "Скасування виклику сервісної служби", "Отмена вызова сервисной службы", "Service call cancelled"),
		evt(dt, 621, "E", 0, "EVENT_LOG_RESET", 0, "Скидання пам'яті подій", "Сброс памяти событий", "Reset event memory"),
		evt(dt, 622, "E", 0, "MEMORY_50_FULL", 0, "Пам'ять заповнена на 50%", "Память заполнена на 50%", "Memory 50% full"),
		evt(dt, 623, "E", 0, "MEMORY_90_FULL", 0, "Пам'ять заповнена на 90%", "Память заполнена на 90%", "Memory 90% full"),
		evt(dt, 624, "E", 0, "MEMORY_OVERFLOW", 1, "Переповнення пам'яті подій пристрою", "Переполнение памяти событий устройства", "Device event memory overflow"),
		evt(dt, 625, "E", 0, "DATETIME_RESET", 0, "Скидання Час/Дата", "Сброс Время/Дата", "Reset Time/Date"),
		evt(dt, 626, "E", 0, "DATETIME_WRONG", 0, "Системний час/дата не коректні", "Системное время/дата не корректны", "System time/date incorrect"),
		evt(dt, 626, "R", 0, "DATETIME_OK", 0, "Системний час/дата коректні", "Системное время/дата корректны", "System time/date correct"),
		evt(dt, 641, "E", 0, "DETECTOR_PROBLEM", 0, "Проблема детектора", "Проблема детектора", "Detector problem"),
		evt(dt, 641, "R", 0, "DETECTOR_RESTORE", 0, "Норма детектора", "Норма детектора", "Detector rate"),
		evt(dt, 654, "E", 0, "SYSTEM_INACTIVE", 0, "Система не активна", "Система не активна", "System is not active"),
		evt(dt, 660, "E", 0, "DOWNLOAD_SUCCESS_FIRMWARE", 0, "Успішне завантаження прошивки", "Успешная загрузка прошивки", "Successful firmware download"),
		evt(dt, 661, "E", 0, "UPDATING_SUCCESS_FIRMWARE", 0, "Успішне оновлення прошивки завершено", "Успешное обновление прошивки завершено", "Successful firmware update"),
		evt(dt, 760, "E", 0, "SIM_SETTINGS_ERROR", 0, "Помилка в налаштуваннях SIM картки", "Ошибка в настройках SIM карты", "SIM card settings error"),
		evt(dt, 836, "E", 0, "DTMF_KEY_REQUEST", 0, "Запит ключа шифрування DTMF", "Запрос ключа шифрования DTMF", "DTMF encryption key request"),
	}
}

// phoenixCIDEventTypes returns the comprehensive Phoenix MSSQL event code table.
// Phoenix uses Contact ID protocol codes with additional type-message-based mapping.
func phoenixCIDEventTypes(dt string) []UnifiedEventType {
	base := cidEventTypes(dt)
	// Phoenix-specific extra codes derived from type_message matching
	extra := []UnifiedEventType{
		evt(dt, 130, "E", 1, "PHOENIX_BURGLARY", 1, "Тривога Phoenix", "Тревога Phoenix", "Phoenix burglary alarm"),
		evt(dt, 100, "E", 1, "PHOENIX_MEDICAL", 1, "Медична тривога Phoenix", "Медицинская тревога Phoenix", "Phoenix medical alarm"),
		evt(dt, 302, "E", 0, "PHOENIX_BATT_LOW", 0, "Проблема АКБ Phoenix", "Проблема АКБ Phoenix", "Phoenix battery low"),
		evt(dt, 302, "R", 0, "PHOENIX_BATT_OK", 0, "АКБ Phoenix норма", "АКБ Phoenix норма", "Phoenix battery restore"),
		evt(dt, 383, "E", 1, "PHOENIX_TAMPER", 1, "Тривога тампера Phoenix", "Тревога тампера Phoenix", "Phoenix tamper alarm"),
		evt(dt, 383, "R", 0, "PHOENIX_TAMPER_RESTORE", 0, "Відновлення тампера Phoenix", "Восстановление тампера Phoenix", "Phoenix tamper restore"),
	}
	return append(base, extra...)
}

// mostBridgeEventTypes returns the event code table for MOST/Firebird bridge devices.
// MOST uses SC1 field values which map to a subset of Contact ID codes.
func mostBridgeEventTypes(dt string) []UnifiedEventType {
	return []UnifiedEventType{
		// SC1=1 → fire
		evt(dt, 110, "E", 1, "MOST_FIRE_ALARM", 1, "Пожежна тривога Міст", "Пожарная тревога Мост", "Bridge fire alarm"),
		evt(dt, 110, "R", 1, "MOST_FIRE_RESTORE", 0, "Відновлення пожежі Міст", "Восстановление пожара Мост", "Bridge fire restore"),
		// SC1=1 → also burglary / panic
		evt(dt, 130, "E", 1, "MOST_BURGLARY", 1, "Охоронна тривога Міст", "Охранная тревога Мост", "Bridge burglary alarm"),
		evt(dt, 130, "R", 1, "MOST_BURGLARY_RESTORE", 0, "Відновлення охоронної тривоги Міст", "Восстановление охранной тревоги Мост", "Bridge burglary restore"),
		evt(dt, 120, "E", 1, "MOST_PANIC", 1, "Тривожна кнопка Міст", "Тревожная кнопка Мост", "Bridge panic alarm"),
		evt(dt, 120, "R", 1, "MOST_PANIC_RESTORE", 0, "Відновлення тривожної кнопки Міст", "Восстановление тревожной кнопки Мост", "Bridge panic restore"),
		evt(dt, 100, "E", 1, "MOST_MEDICAL", 1, "Медична тривога Міст", "Медицинская тревога Мост", "Bridge medical alarm"),
		evt(dt, 151, "E", 1, "MOST_GAS", 1, "Газова тривога Міст", "Газовая тревога Мост", "Bridge gas alarm"),
		evt(dt, 151, "R", 1, "MOST_GAS_RESTORE", 0, "Відновлення газової тривоги Міст", "Восстановление газовой тревоги Мост", "Bridge gas restore"),
		// SC1=2,3 → fault (zone break / short circuit)
		evt(dt, 380, "E", 0, "MOST_ZONE_FAULT", 0, "Несправність зони Міст", "Неисправность зоны Мост", "Bridge zone fault"),
		evt(dt, 380, "R", 0, "MOST_ZONE_FAULT_RESTORE", 0, "Відновлення несправності зони Міст", "Восстановление неисправности зоны Мост", "Bridge zone fault restore"),
		evt(dt, 331, "E", 0, "MOST_LOOP_BREAK", 1, "Обрив шлейфу Міст", "Обрыв шлейфа Мост", "Bridge sensor loop break"),
		evt(dt, 331, "R", 0, "MOST_LOOP_BREAK_RESTORE", 0, "Відновлення обриву шлейфу Міст", "Восстановление обрыва шлейфа Мост", "Bridge sensor loop restore"),
		evt(dt, 332, "E", 0, "MOST_LOOP_SHORT", 1, "КЗ шлейфу Міст", "КЗ шлейфа Мост", "Bridge sensor loop short circuit"),
		evt(dt, 332, "R", 0, "MOST_LOOP_SHORT_RESTORE", 0, "Відновлення КЗ шлейфу Міст", "Восстановление КЗ шлейфа Мост", "Bridge sensor loop short circuit restore"),
		// SC1=5,9,13,17 → restore
		evt(dt, 110, "R", 1, "MOST_RESTORE", 0, "Відновлення тривоги Міст", "Восстановление тревоги Мост", "Bridge alarm restore"),
		// SC1=10 → arm
		evt(dt, 401, "E", 0, "MOST_ARM", 0, "Постановка під охорону Міст", "Постановка под охрану Мост", "Bridge armed"),
		evt(dt, 401, "R", 0, "MOST_DISARM", 0, "Зняття з охорони Міст", "Снятие с охраны Мост", "Bridge disarmed"),
		// SC1=11,14,18 → disarm
		evt(dt, 402, "E", 0, "MOST_DISARM", 0, "Зняття з охорони Міст", "Снятие с охраны Мост", "Bridge disarmed"),
		evt(dt, 402, "R", 0, "MOST_ARM", 0, "Постановка під охорону Міст", "Постановка под охрану Мост", "Bridge armed"),
		// SC1=12 → offline / online
		evt(dt, 359, "E", 0, "MOST_DEVICE_OFFLINE", 1, "Немає зв'язку Міст", "Нет связи Мост", "Bridge device offline"),
		evt(dt, 359, "R", 0, "MOST_DEVICE_ONLINE", 0, "Зв'язок Міст відновлено", "Связь Мост восстановлена", "Bridge device online"),
		// AC power
		evt(dt, 301, "E", 0, "MOST_AC_LOSS", 0, "Втрата живлення Міст", "Потеря питания Мост", "Bridge AC loss"),
		evt(dt, 301, "R", 0, "MOST_AC_RESTORE", 0, "Живлення Міст відновлено", "Питание Мост восстановлено", "Bridge AC restore"),
		evt(dt, 302, "E", 0, "MOST_BATT_LOW", 0, "Низький заряд АКБ Міст", "Низкий заряд АКБ Мост", "Bridge battery low"),
		evt(dt, 302, "R", 0, "MOST_BATT_RESTORE", 0, "АКБ Міст відновлено", "АКБ Мост восстановлено", "Bridge battery restore"),
		// tamper
		evt(dt, 383, "E", 0, "MOST_TAMPER", 1, "Тампер Міст", "Тампер Мост", "Bridge tamper"),
		evt(dt, 383, "R", 0, "MOST_TAMPER_RESTORE", 0, "Відновлення тампера Міст", "Восстановление тампера Мост", "Bridge tamper restore"),
		// test
		evt(dt, 602, "E", 0, "MOST_TEST", 0, "Тест Міст", "Тест Мост", "Bridge test"),
		// partial arm/disarm (SC1=14,18)
		evt(dt, 404, "E", 2, "MOST_PARTIAL_DISARM", 0, "Часткове зняття групи Міст", "Частичное снятие группы Мост", "Bridge partial disarm"),
		evt(dt, 403, "E", 2, "MOST_AUTO_DISARM", 0, "Автоматичне зняття групи Міст", "Автоматическое снятие группы Мост", "Bridge auto disarm"),
	}
}
