// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AssignResponseGroup(arg1, arg2) {
  return window['go']['wailsbridge']['FrontendV1Service']['AssignResponseGroup'](arg1, arg2);
}

export function CancelResponseGroup(arg1) {
  return window['go']['wailsbridge']['FrontendV1Service']['CancelResponseGroup'](arg1);
}

export function Capabilities() {
  return window['go']['wailsbridge']['FrontendV1Service']['Capabilities']();
}

export function GetAlarmProcessingOptions(arg1) {
  return window['go']['wailsbridge']['FrontendV1Service']['GetAlarmProcessingOptions'](arg1);
}

export function GetObjectDetails(arg1) {
  return window['go']['wailsbridge']['FrontendV1Service']['GetObjectDetails'](arg1);
}

export function GroupProcessAlarm(arg1, arg2) {
  return window['go']['wailsbridge']['FrontendV1Service']['GroupProcessAlarm'](arg1, arg2);
}

export function IsReady() {
  return window['go']['wailsbridge']['FrontendV1Service']['IsReady']();
}

export function ListAlarmGroups() {
  return window['go']['wailsbridge']['FrontendV1Service']['ListAlarmGroups']();
}

export function ListAlarmProcessingOptionsCached() {
  return window['go']['wailsbridge']['FrontendV1Service']['ListAlarmProcessingOptionsCached']();
}

export function ListAlarms() {
  return window['go']['wailsbridge']['FrontendV1Service']['ListAlarms']();
}

export function ListEvents() {
  return window['go']['wailsbridge']['FrontendV1Service']['ListEvents']();
}

export function ListObjectEvents(arg1, arg2, arg3) {
  return window['go']['wailsbridge']['FrontendV1Service']['ListObjectEvents'](arg1, arg2, arg3);
}

export function ListObjects() {
  return window['go']['wailsbridge']['FrontendV1Service']['ListObjects']();
}

export function ListResponseGroups() {
  return window['go']['wailsbridge']['FrontendV1Service']['ListResponseGroups']();
}

export function NotifyGroupArrived(arg1) {
  return window['go']['wailsbridge']['FrontendV1Service']['NotifyGroupArrived'](arg1);
}

export function PickAlarm(arg1, arg2) {
  return window['go']['wailsbridge']['FrontendV1Service']['PickAlarm'](arg1, arg2);
}

export function ProcessAlarm(arg1, arg2) {
  return window['go']['wailsbridge']['FrontendV1Service']['ProcessAlarm'](arg1, arg2);
}

export function SetBackend(arg1) {
  return window['go']['wailsbridge']['FrontendV1Service']['SetBackend'](arg1);
}

export function StandbyObject(arg1, arg2, arg3) {
  return window['go']['wailsbridge']['FrontendV1Service']['StandbyObject'](arg1, arg2, arg3);
}
